## Components [/v1/components/categories]

### GET Component Categories [GET]
Get all available Component Categories

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
                {
                    "name": "Propulsion",
                    "slug": "propulsion"
                },
                {
                    "name": "Ordnance",
                    "slug": "ordnance"
                },
                {
                    "name": "Modular",
                    "slug": "modular"
                },
                {
                    "name": "Avionics",
                    "slug": "avionics"
                }
            ]
