#!/bin/sh

DEST_FLAG=""
if [ -n "$KAMAL_DESTINATION" ]; then
  DEST_FLAG="-d $KAMAL_DESTINATION"
fi

echo "Running database migrations..."
kamal app exec $DEST_FLAG --roles=web --primary --version="$KAMAL_VERSION" 'bin/rails db:migrate'

echo "Running data migrations..."
kamal app exec $DEST_FLAG --roles=web --primary --version="$KAMAL_VERSION" 'bin/rails data:migrate'
