/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Box: typeof import('./shared/components/base/Box/index.vue')['default']
    Btn: typeof import('./shared/components/base/Btn/index.vue')['default']
    BtnDropdown: typeof import('./shared/components/base/BtnDropdown/index.vue')['default']
    BtnGroup: typeof import('./shared/components/base/BtnGroup/index.vue')['default']
    BtnInner: typeof import('./shared/components/base/Btn/Inner/index.vue')['default']
    FilterGroup: typeof import('./shared/components/base/FilterGroup/index.vue')['default']
    FilterGroupOption: typeof import('./shared/components/base/FilterGroup/Option/index.vue')['default']
    FormActions: typeof import('./shared/components/base/FormActions/index.vue')['default']
    FormCheckbox: typeof import('./shared/components/base/FormCheckbox/index.vue')['default']
    FormImageInput: typeof import('./shared/components/base/FormImageInput/index.vue')['default']
    FormInput: typeof import('./shared/components/base/FormInput/index.vue')['default']
    FormTextarea: typeof import('./shared/components/base/FormTextarea/index.vue')['default']
    Grid: typeof import('./shared/components/base/Grid/index.vue')['default']
    Heading: typeof import('./shared/components/base/Heading/index.vue')['default']
    HeadingSmall: typeof import('./shared/components/base/Heading/Small/index.vue')['default']
    Pill: typeof import('./shared/components/base/Pill/index.vue')['default']
    RadioList: typeof import('./shared/components/base/RadioList/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table: typeof import('./shared/components/base/Table/index.vue')['default']
    TableActions: typeof import('./shared/components/base/Table/Actions/index.vue')['default']
    Text: typeof import('./shared/components/base/Text/index.vue')['default']
  }
}
