export default () => ({
  detailsVisible: false,
  filterVisible: true,
  fleetchartLabels: false,
  fleetchartMode: 'panzoom',
  fleetchartScale: 1,
  fleetchartScreenHeight: '1x',
  fleetchartViewpoint: 'side',
  fleetchartVisible: false,
  fleetchartZoomData: null,
  gridView: true,
  money: true,
  perPage: 30,
  preview: true,
  ships: [],
  starterGuideVisible: false,
  tableSlim: false,
})
