version: 2

updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - ruby

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - javascript
    groups:
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
      playwright:
        patterns:
          - "playwright"
          - "@playwright/*"

  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - docker

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
