## Shop [/v1/stations/{station_slug}/shops/{slug}]

### GET Detail [GET]
Get Detail of a Shop referenced by its Slug and its Station Slug

+ Parameters

    + station_slug: `port-olisar` (required, string) - The Station Slug
    + slug: `dumpers-depot` (required, string) - The Shop Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            {
            }
