preserve_hierarchy: 1
files:
  - source: /config/locales/en/*.yml
    translation: /config/locales/%two_letters_code%/%original_file_name%
  - source: /app/frontend/translations/en/*.js
    translation: /app/frontend/translations/%two_letters_code%/%original_file_name%
