packages:
  - '.'
allowBuilds:
  '@hyperjump/json-pointer': false
  '@hyperjump/json-schema': false
  '@hyperjump/json-schema-core': false
  '@hyperjump/pact': false
  '@parcel/watcher': false
  '@scarf/scarf': false
  core-js: false
  esbuild: true
  msw: false
  vue-demi: false
peerDependencyRules:
  allowedVersions:
    vite-plugin-pwa>vite: '8'
overrides:
  json5: '>=2.2.2'
  semver: '>=7.5.2'
  picomatch: '>=4.0.4'
  serialize-javascript: '>=7.0.5'
  ajv@5: '>=6.14.0 <7'
  ajv@6: '>=6.14.0 <7'
  jsonpath-plus@7: '>=10.3.0'
  js-yaml@4: '>=4.3.2 <5'
patchedDependencies:
  '@tresjs/core@5.8.1': patches/@tresjs__core@5.8.1.patch
