## Models [/v1/models]

### GET List [GET]
Get a List of Models

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
                {
                    "id": "719f60e4-ae48-4941-80f1-17528fd7dd06",
                    "name": "100i",
                    "rsiName": "100i",
                    "slug": "100i",
                    "rsiSlug": "100i",
                    "description": "Tour the universe with the perfect coupling of luxury and performance. The 100i features Origin Jumpworks' patented AIR fuel system, making it the most efficient and eco-friendly ship on the market. Capable of long distance flights that most ships of its size aren't equipped for, the 100i is perfect for solo pilots looking to turn heads without sacrificing functionality or reliability.",
                    "length": 15,
                    "beam": 10,
                    "height": 4,
                    "mass": 0,
                    "cargo": 2,
                    "cargoLabel": "100i (2 SCU)",
                    "minCrew": 1,
                    "maxCrew": 1,
                    "scmSpeed": "210.0",
                    "afterburnerSpeed": null,
                    "groundSpeed": null,
                    "afterburnerGroundSpeed": null,
                    "pitchMax": null,
                    "yawMax": null,
                    "rollMax": null,
                    "xaxisAcceleration": null,
                    "yaxisAcceleration": null,
                    "zaxisAcceleration": null,
                    "size": "small",
                    "sizeLabel": "Small",
                    "storeImage": "http://api.fleetyards.test/uploads/model/store_image/719f60e4-ae48-4941-80f1-17528fd7dd06/100i.jpg",
                    "fleetchartImage": "http://api.fleetyards.test/uploads/model/fleetchart_image/719f60e4-ae48-4941-80f1-17528fd7dd06/100i.png",
                    "backgroundImage": "http://api.fleetyards.test/uploads/image/name/1c6093b0-7dad-498a-bb4e-a3d12a843990/ORIG_100i_Interior_design_Shot_AL03_CC-Min.jpg",
                    "brochure": "http://api.fleetyards.test/uploads/model/brochure/719f60e4-ae48-4941-80f1-17528fd7dd06/Origin-100-Series-Brochure-FINAL.pdf",
                    "storeUrl": "https://robertsspaceindustries.com/pledge/ships/origin-100/100i",
                    "price": null,
                    "pledgePrice": 40,
                    "lastPledgePrice": 45,
                    "onSale": false,
                    "productionStatus": "in-concept",
                    "productionNote": null,
                    "classification": "multi",
                    "classificationLabel": "Multi",
                    "focus": "Starter/Touring",
                    "rsiId": 159,
                    "hasImages": true,
                    "hasVideos": false,
                    "manufacturer": {
                        "name": "Origin Jumpworks GmbH",
                        "slug": "origin-jumpworks-gmbh",
                        "code": "ORIG",
                        "logo": "http://api.fleetyards.test/uploads/manufacturer/logo/4052e7cf-5451-4a9f-a7e2-797daa26ccd8/small_Origin.png"
                    },
                    "createdAt": "2018-04-13T21:16:02+02:00",
                    "updatedAt": "2018-05-02T08:31:16+02:00"
                },
                ...
            ]
