## Model [/v1/models/{slug}/images]

### GET Images [GET]
Get Image List of a Model referenced by its Slug

+ Parameters

    + slug: `cutlass-black` (required, string) - The Model Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            [
                {
                    "id": "67438138-d329-43af-b64c-ced601927a3a",
                    "name": "1486925107.jpg",
                    "url": "http://api.fleetyards.test/uploads/image/name/67438138-d329-43af-b64c-ced601927a3a/1486925107.jpg",
                    "width": 827,
                    "height": 344,
                    "type": "image/jpeg",
                    "background": true,
                    "smallUrl": "http://api.fleetyards.test/uploads/image/name/67438138-d329-43af-b64c-ced601927a3a/small_1486925107.jpg",
                    "bigUrl": "http://api.fleetyards.test/uploads/image/name/67438138-d329-43af-b64c-ced601927a3a/big_1486925107.jpg",
                    "model": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "gallery": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "createdAt": "2017-10-19T23:45:35+02:00",
                    "updatedAt": "2017-10-27T14:19:07+02:00"
                },
                {
                    "id": "0752ca78-1a3f-4c1c-9b26-d57cb35681d3",
                    "name": "1486925107__2_.jpg",
                    "url": "http://api.fleetyards.test/uploads/image/name/0752ca78-1a3f-4c1c-9b26-d57cb35681d3/1486925107__2_.jpg",
                    "width": 879,
                    "height": 344,
                    "type": "image/jpeg",
                    "background": true,
                    "smallUrl": "http://api.fleetyards.test/uploads/image/name/0752ca78-1a3f-4c1c-9b26-d57cb35681d3/small_1486925107__2_.jpg",
                    "bigUrl": "http://api.fleetyards.test/uploads/image/name/0752ca78-1a3f-4c1c-9b26-d57cb35681d3/big_1486925107__2_.jpg",
                    "model": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "gallery": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "createdAt": "2017-10-19T23:45:35+02:00",
                    "updatedAt": "2017-10-27T14:19:07+02:00"
                },
                {
                    "id": "e2abace5-1839-46ac-9c73-3337a823b83b",
                    "name": "1486925107__1_.jpg",
                    "url": "http://api.fleetyards.test/uploads/image/name/e2abace5-1839-46ac-9c73-3337a823b83b/1486925107__1_.jpg",
                    "width": 736,
                    "height": 344,
                    "type": "image/jpeg",
                    "background": true,
                    "smallUrl": "http://api.fleetyards.test/uploads/image/name/e2abace5-1839-46ac-9c73-3337a823b83b/small_1486925107__1_.jpg",
                    "bigUrl": "http://api.fleetyards.test/uploads/image/name/e2abace5-1839-46ac-9c73-3337a823b83b/big_1486925107__1_.jpg",
                    "model": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "gallery": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "createdAt": "2017-10-19T23:45:35+02:00",
                    "updatedAt": "2017-10-27T14:19:08+02:00"
                },
                {
                    "id": "6bf13569-1071-419e-b307-3f23bd8dd034",
                    "name": "Drake_Cutlass_Black_InFlight-Copy.jpg",
                    "url": "http://api.fleetyards.test/uploads/image/name/6bf13569-1071-419e-b307-3f23bd8dd034/Drake_Cutlass_Black_InFlight-Copy.jpg",
                    "width": 4000,
                    "height": 1938,
                    "type": "image/jpeg",
                    "background": true,
                    "smallUrl": "http://api.fleetyards.test/uploads/image/name/6bf13569-1071-419e-b307-3f23bd8dd034/small_Drake_Cutlass_Black_InFlight-Copy.jpg",
                    "bigUrl": "http://api.fleetyards.test/uploads/image/name/6bf13569-1071-419e-b307-3f23bd8dd034/big_Drake_Cutlass_Black_InFlight-Copy.jpg",
                    "model": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "gallery": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "createdAt": "2017-10-19T23:38:24+02:00",
                    "updatedAt": "2017-10-27T14:19:07+02:00"
                },
                {
                    "id": "8f6366ab-d161-41c7-9a2d-886c4c778c0a",
                    "name": "maxresdefault.jpg",
                    "url": "http://api.fleetyards.test/uploads/image/name/8f6366ab-d161-41c7-9a2d-886c4c778c0a/maxresdefault.jpg",
                    "width": 1280,
                    "height": 720,
                    "type": "image/jpeg",
                    "background": true,
                    "smallUrl": "http://api.fleetyards.test/uploads/image/name/8f6366ab-d161-41c7-9a2d-886c4c778c0a/small_maxresdefault.jpg",
                    "bigUrl": "http://api.fleetyards.test/uploads/image/name/8f6366ab-d161-41c7-9a2d-886c4c778c0a/big_maxresdefault.jpg",
                    "model": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "gallery": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "createdAt": "2017-10-19T23:38:07+02:00",
                    "updatedAt": "2017-10-27T14:19:07+02:00"
                },
                {
                    "id": "a2fd3a43-bcf3-4d1e-bcb7-86b00621fca8",
                    "name": "maxresdefault__1_.jpg",
                    "url": "http://api.fleetyards.test/uploads/image/name/a2fd3a43-bcf3-4d1e-bcb7-86b00621fca8/maxresdefault__1_.jpg",
                    "width": 1280,
                    "height": 720,
                    "type": "image/jpeg",
                    "background": true,
                    "smallUrl": "http://api.fleetyards.test/uploads/image/name/a2fd3a43-bcf3-4d1e-bcb7-86b00621fca8/small_maxresdefault__1_.jpg",
                    "bigUrl": "http://api.fleetyards.test/uploads/image/name/a2fd3a43-bcf3-4d1e-bcb7-86b00621fca8/big_maxresdefault__1_.jpg",
                    "model": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "gallery": {
                        "id": "b94e105b-8b8c-47f0-975c-5e6a3d1a3134",
                        "name": "Cutlass Black",
                        "slug": "cutlass-black"
                    },
                    "createdAt": "2017-10-19T23:38:06+02:00",
                    "updatedAt": "2017-10-27T14:19:08+02:00"
                }
            ]
