## Models [/v1/models]

### GET List [GET]
Get a List of Models

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
                {
                    "id": "4a624dcc-5e61-4166-822a-2d918edc5910",
                    "name": "300i",
                    "rsiName": "300i",
                    "slug": "300i",
                    "rsiSlug": "300i",
                    "description": "If you're going to travel the stars... why not do it in style? The 300i is Origin Jumpworks' premiere luxury spacecraft. It is a sleek, silver killer that sends as much of a message with its silhouette as it does with its weaponry.",
                    "length": 23,
                    "beam": 15.5,
                    "height": 7,
                    "mass": 46195.5,
                    "cargo": "2.0",
                    "minCrew": 1,
                    "maxCrew": 1,
                    "scmSpeed": "275.0",
                    "afterburnerSpeed": "1190.0",
                    "groundSpeed": null,
                    "afterburnerGroundSpeed": null,
                    "pitchMax": "85.0",
                    "yawMax": "85.0",
                    "rollMax": "120.0",
                    "xaxisAcceleration": "68.0",
                    "yaxisAcceleration": "80.3",
                    "zaxisAcceleration": "71.7",
                    "size": "small",
                    "storeImage": "https://api.fleetyards.net/uploads/model/store_image/4a624dcc-5e61-4166-822a-2d918edc5910/300i_storefront_visual-1450470207.jpg",
                    "fleetchartImage": "https://api.fleetyards.net/uploads/model/fleetchart_image/4a624dcc-5e61-4166-822a-2d918edc5910/ORIG_-_300i-1519582086.png",
                    "brochure": null,
                    "storeUrl": "https://robertsspaceindustries.com/pledge/ships/origin-300/300i",
                    "price": "100000.0",
                    "pledgePrice": "55.0",
                    "lastPledgePrice": "55.0",
                    "onSale": true,
                    "productionStatus": "flight-ready",
                    "productionNote": "Update Pass Scheduled",
                    "classification": "exploration",
                    "classificationLabel": "Exploration",
                    "focus": "Touring",
                    "rsiId": 7,
                    "manufacturer": {
                        "name": "Origin Jumpworks GmbH",
                        "slug": "origin-jumpworks-gmbh",
                        "code": "ORIG",
                        "logo": "https://api.fleetyards.net/uploads/manufacturer/logo/4052e7cf-5451-4a9f-a7e2-797daa26ccd8/small_Origin.png"
                    },
                    "createdAt": "2014-10-04T23:45:27+02:00",
                    "updatedAt": "2018-06-28T16:45:16+02:00"
                }
            ]
