## Model [/v1/models/{slug}]

### GET Detail [GET]
Get Detail of a Model referenced by its Slug

+ Parameters

    + slug: `origin-600i-explorer` (required, string) - The Model Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            {
                "id": "4a624dcc-5e61-4166-822a-2d918edc5910",
                "name": "300i",
                "rsiName": "300i",
                "slug": "300i",
                "rsiSlug": "300i",
                "description": "If you're going to travel the stars... why not do it in style? The 300i is Origin Jumpworks' premiere luxury spacecraft. It is a sleek, silver killer that sends as much of a message with its silhouette as it does with its weaponry.",
                "length": 23,
                "beam": 15.5,
                "height": 7,
                "mass": 46195.5,
                "cargo": "2.0",
                "minCrew": 1,
                "maxCrew": 1,
                "scmSpeed": "275.0",
                "afterburnerSpeed": "1190.0",
                "groundSpeed": null,
                "afterburnerGroundSpeed": null,
                "pitchMax": "85.0",
                "yawMax": "85.0",
                "rollMax": "120.0",
                "xaxisAcceleration": "68.0",
                "yaxisAcceleration": "80.3",
                "zaxisAcceleration": "71.7",
                "size": "small",
                "storeImage": "https://api.fleetyards.net/uploads/model/store_image/4a624dcc-5e61-4166-822a-2d918edc5910/300i_storefront_visual-1450470207.jpg",
                "fleetchartImage": "https://api.fleetyards.net/uploads/model/fleetchart_image/4a624dcc-5e61-4166-822a-2d918edc5910/ORIG_-_300i-1519582086.png",
                "brochure": null,
                "storeUrl": "https://robertsspaceindustries.com/pledge/ships/origin-300/300i",
                "price": "100000.0",
                "pledgePrice": "55.0",
                "lastPledgePrice": "55.0",
                "onSale": true,
                "productionStatus": "flight-ready",
                "productionNote": "Update Pass Scheduled",
                "classification": "exploration",
                "classificationLabel": "Exploration",
                "focus": "Touring",
                "rsiId": 7,
                "manufacturer": {
                    "name": "Origin Jumpworks GmbH",
                    "slug": "origin-jumpworks-gmbh",
                    "code": "ORIG",
                    "logo": "https://api.fleetyards.net/uploads/manufacturer/logo/4052e7cf-5451-4a9f-a7e2-797daa26ccd8/small_Origin.png"
                },
                "hardpoints": [
                    {
                        "id": "8180e5ef-c42a-4a8e-a29e-8e25803ac79a",
                        "type": "radar",
                        "class": "RSIAvionic",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "4c35c500-e8c7-4485-9b25-db3a59b699bf",
                        "type": "computers",
                        "class": "RSIAvionic",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "603298b2-6079-4a0d-ac46-6e91ae32ecb6",
                        "type": "fuel_intakes",
                        "class": "RSIPropulsion",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 2,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "a5857977-1d3c-462f-9897-4e82a917b8e4",
                        "type": "fuel_tanks",
                        "class": "RSIPropulsion",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 2,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "617f3e6a-63ff-460e-86a2-813dc6faaaeb",
                        "type": "quantum_drives",
                        "class": "RSIPropulsion",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "67e368fd-b6a4-46b9-bb41-1cbf312ebfa7",
                        "type": "jump_modules",
                        "class": "RSIPropulsion",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "7e34b918-d736-45c9-bcd3-666d826b5a1f",
                        "type": "quantum_fuel_tanks",
                        "class": "RSIPropulsion",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "cd4e06b6-3d0d-42a3-9fd6-04bc16804c6f",
                        "type": "main_thrusters",
                        "class": "RSIThruster",
                        "size": "-",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": "M",
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "3cc63cf7-6af8-4245-a185-9d209463146c",
                        "type": "maneuvering_thrusters",
                        "class": "RSIThruster",
                        "size": "-",
                        "quantity": 1,
                        "mounts": 12,
                        "details": "",
                        "category": "G",
                        "defaultEmpty": false,
                        "component": null
                    },
                    {
                        "id": "7cf99767-2e1c-4ecf-b187-2e014011f60c",
                        "type": "power_plants",
                        "class": "RSIModular",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": {
                            "id": "b60bd8fe-eedf-447e-894e-f4be04bec439",
                            "name": "Roughneck",
                            "slug": "roughneck",
                            "size": "S",
                            "class": "RSIModular",
                            "type": "power_plants",
                            "manufacturer": {
                                "name": "Juno Starwerk",
                                "slug": "juno-starwerk"
                            }
                        }
                    },
                    {
                        "id": "880990a7-9725-4c3a-8362-0d8aa85b07dd",
                        "type": "coolers",
                        "class": "RSIModular",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 2,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": {
                            "id": "17efcc7c-6280-4f11-8ad0-3bd2c32808ba",
                            "name": "Hydrocel",
                            "slug": "hydrocel",
                            "size": "S",
                            "class": "RSIModular",
                            "type": "coolers",
                            "manufacturer": {
                                "name": "Juno Starwerk",
                                "slug": "juno-starwerk"
                            }
                        }
                    },
                    {
                        "id": "52a9088d-b517-44f9-8886-e969f53ed83c",
                        "type": "shield_generators",
                        "class": "RSIModular",
                        "size": "S",
                        "quantity": 1,
                        "mounts": 2,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": {
                            "id": "1a0649e3-7c03-4f2c-9eee-be156527b734",
                            "name": "Steward",
                            "slug": "steward",
                            "size": "S",
                            "class": "RSIModular",
                            "type": "shield_generators",
                            "manufacturer": {
                                "name": "Basilisk",
                                "slug": "basilisk"
                            }
                        }
                    },
                    {
                        "id": "049549d8-f972-421d-ae53-33dd69eacdb9",
                        "type": "weapons",
                        "class": "RSIWeapon",
                        "size": "2",
                        "quantity": 1,
                        "mounts": 2,
                        "details": "",
                        "category": null,
                        "defaultEmpty": false,
                        "component": {
                            "id": "a3507f77-f0b8-4d4c-b504-0c0b1f994194",
                            "name": "Omnisky VI Laser Cannon",
                            "slug": "omnisky-vi-laser-cannon",
                            "size": "2",
                            "class": "RSIWeapon",
                            "type": "weapons",
                            "manufacturer": {
                                "name": "Amon &amp; Reese Co.",
                                "slug": "amon-amp-reese-co"
                            }
                        }
                    },
                    {
                        "id": "9d007ac7-2dcd-4f30-b04f-44d352ac9968",
                        "type": "weapons",
                        "class": "RSIWeapon",
                        "size": "3",
                        "quantity": 1,
                        "mounts": 1,
                        "details": "",
                        "category": null,
                        "defaultEmpty": true,
                        "component": null
                    },
                    {
                        "id": "d9c75b51-5ff9-41ed-b87b-1780e4011b3b",
                        "type": "missiles",
                        "class": "RSIWeapon",
                        "size": "1",
                        "quantity": 1,
                        "mounts": 2,
                        "details": "Behring MSD-111 ",
                        "category": null,
                        "defaultEmpty": false,
                        "component": {
                            "id": "b6681949-9e6f-4904-ab9d-446bd99438d3",
                            "name": "Pioneer I",
                            "slug": "pioneer-i",
                            "size": "1",
                            "class": "RSIWeapon",
                            "type": "missiles",
                            "manufacturer": {
                                "name": "Behring",
                                "slug": "behring",
                                "logo": "https://api.fleetyards.net/uploads/manufacturer/logo/6325fdbf-476c-4bb4-b498-4a3ff7260851/small_Behring.png"
                            }
                        }
                    }
                ],
                "images": [],
                "videos": [],
                "createdAt": "2014-10-04T23:45:27+02:00",
                "updatedAt": "2018-06-28T16:45:16+02:00"
            }
