## Models [/v1/models/slugs]

### GET List [GET]
Get a List of all current Model slugs

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
                "eclipse",
                "mercury-star-runner",
                "geotack-x-planetary-beacon",
                "avenger-warlock",
                "avenger-titan-renegade",
                "avenger-titan",
                "hurricane",
                "blade",
                "cutlass-black",
                "avenger-stalker",
                "600i-explorer",
                "gladius",
                "reclaimer",
                "f7c-r-hornet-tracker",
                "razor",
                "reliant-sen",
                "dragonfly-black",
                "f7c-m-super-hornet",
                "nox-kue",
                "mpuv-cargo",
                "m50",
                "vulture",
                "endeavor",
                "cyclone-aa",
                "hammerhead",
                "freelancer-mis",
                "f8c",
                "buccaneer",
                "prowler",
                "hull-a",
                "p52-merlin",
                "hawk",
                "hull-c",
                "x1-velocity",
                "retaliator-bomber",
                "carrack",
                "scythe",
                "crucible",
                "f7c-hornet-wildfire",
                "redeemer",
                "ptv",
                "300i",
                "khartu-al",
                "315p",
                "constellation-aquila",
                "aurora-lx",
                "gladius-valiant",
                "reliant-mako",
                "reliant-tana",
                "x1-force",
                "idris-m",
                "cyclone-rc",
                "p72-archimedes",
                "constellation-taurus",
                "mpuv-personnel",
                "cyclone",
                "325a",
                "constellation-phoenix",
                "genesis-starliner",
                "sabre-comet",
                "razor-ex",
                "nox",
                "cyclone-tr",
                "350r",
                "idris-p",
                "javelin",
                "sabre",
                "herald",
                "cyclone-rn",
                "polaris",
                "vanguard-warden",
                "f7a-hornet",
                "freelancer-max",
                "pioneer",
                "890-jump",
                "apollo-triage",
                "nova",
                "85x",
                "x1-base",
                "glaive",
                "merchantman",
                "starfarer-gemini",
                "sabre-raven",
                "dragonfly-yellowjacket",
                "gladiator",
                "ursa-rover",
                "freelancer",
                "freelancer-dur",
                "hull-e",
                "f7c-hornet",
                "aurora-cl",
                "hull-b",
                "constellation-andromeda",
                "100i",
                "vanguard-harbinger",
                "aurora-mr",
                "razor-lx",
                "m2-hercules",
                "f8c-executive",
                "135c",
                "aurora-es",
                "aurora-ln",
                "dragonfly-starkitten-edition",
                "125a",
                "vulcan",
                "terrapin",
                "vanguard-hoplite",
                "hull-d",
                "a2-hercules",
                "c2-hercules",
                "mustang-delta",
                "mustang-alpha-vindicator",
                "geotack-planetary-beacon",
                "mustang-alpha",
                "valkyrie-liberator-edition",
                "mustang-gamma",
                "mustang-beta",
                "mustang-omega",
                "prospector",
                "apollo-medivac",
                "cutlass-blue",
                "cutlass-red",
                "kraken",
                "starfarer",
                "caterpillar-pirate-edition",
                "vanguard-sentinel",
                "orion",
                "constellation-phoenix-emerald",
                "arrow",
                "defender",
                "valkyrie",
                "reliant-kore",
                "f7c-s-hornet-ghost",
                "600i-touring",
                "caterpillar",
                "idris-k",
                "san-tok-yai",
                "retaliator-base"
            ]
