## Models [/v1/models/latest]

### GET Latest [GET]
Get the last 20 Models ordered by ```updatedAt```

The Response Body is identical to ```/v1/models```

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)
