/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type { Components, ComponentsParams, StandardError } from "../models";

import { axiosClient } from "../axiosClient";
import type { ErrorType } from "../axiosClient";
import { customQueryOptions } from "../../customQueryOptions";

/**
 * @summary Components list
 */
export const components = (
  params?: MaybeRef<ComponentsParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return axiosClient<Components>({
    url: `/components`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

const getComponentsQueryKey = (params?: MaybeRef<ComponentsParams>) => {
  return ["components", ...(params ? [params] : [])] as const;
};

export const useComponentsQueryOptions = <
  TData = Awaited<ReturnType<typeof components>>,
  TError = ErrorType<StandardError>,
>(
  params?: MaybeRef<ComponentsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof components>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getComponentsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof components>>> = ({
    signal,
  }) => components(params, signal);

  const customOptions = customQueryOptions({
    ...queryOptions,
    queryKey,
    queryFn,
  });

  return customOptions as UseQueryOptions<
    Awaited<ReturnType<typeof components>>,
    TError,
    TData
  >;
};

export type ComponentsQueryResult = NonNullable<
  Awaited<ReturnType<typeof components>>
>;
export type ComponentsQueryError = ErrorType<StandardError>;

/**
 * @summary Components list
 */

export function useComponents<
  TData = Awaited<ReturnType<typeof components>>,
  TError = ErrorType<StandardError>,
>(
  params?: MaybeRef<ComponentsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof components>>, TError, TData>
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = useComponentsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}
