/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";
import { unref } from "vue";
import type { MaybeRef } from "vue";
import type { StandardError, Users, UsersParams } from "../models";
import { axiosClient } from "../axiosClient";
import type { ErrorType } from "../axiosClient";

/**
 * @summary Users list
 */
export const users = (params?: MaybeRef<UsersParams>, signal?: AbortSignal) => {
  params = unref(params);

  return axiosClient<Users>({
    url: `/users`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getUsersQueryKey = (params?: MaybeRef<UsersParams>) => {
  return ["users", ...(params ? [params] : [])] as const;
};

export const getUsersQueryOptions = <
  TData = Awaited<ReturnType<typeof users>>,
  TError = ErrorType<StandardError>,
>(
  params?: MaybeRef<UsersParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof users>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getUsersQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof users>>> = ({
    signal,
  }) => users(params, signal);

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof users>>,
    TError,
    TData
  >;
};

export type UsersQueryResult = NonNullable<Awaited<ReturnType<typeof users>>>;
export type UsersQueryError = ErrorType<StandardError>;

/**
 * @summary Users list
 */

export function useUsers<
  TData = Awaited<ReturnType<typeof users>>,
  TError = ErrorType<StandardError>,
>(
  params?: MaybeRef<UsersParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof users>>, TError, TData>
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = getUsersQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}
