/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type { StandardError, Vehicles, VehiclesParams } from "../models";

import { axiosClient } from "../axiosClient";
import type { ErrorType } from "../axiosClient";
import { customQueryOptions } from "../../customQueryOptions";

/**
 * @summary Vehicles list
 */
export const vehicles = (
  params?: MaybeRef<VehiclesParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return axiosClient<Vehicles>({
    url: `/vehicles`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getVehiclesQueryKey = (params?: MaybeRef<VehiclesParams>) => {
  return ["vehicles", ...(params ? [params] : [])] as const;
};

export const useVehiclesQueryOptions = <
  TData = Awaited<ReturnType<typeof vehicles>>,
  TError = ErrorType<StandardError>,
>(
  params?: MaybeRef<VehiclesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vehicles>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getVehiclesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof vehicles>>> = ({
    signal,
  }) => vehicles(params, signal);

  const customOptions = customQueryOptions({
    ...queryOptions,
    queryKey,
    queryFn,
  });

  return customOptions as UseQueryOptions<
    Awaited<ReturnType<typeof vehicles>>,
    TError,
    TData
  >;
};

export type VehiclesQueryResult = NonNullable<
  Awaited<ReturnType<typeof vehicles>>
>;
export type VehiclesQueryError = ErrorType<StandardError>;

/**
 * @summary Vehicles list
 */

export function useVehicles<
  TData = Awaited<ReturnType<typeof vehicles>>,
  TError = ErrorType<StandardError>,
>(
  params?: MaybeRef<VehiclesParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof vehicles>>, TError, TData>
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = useVehiclesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}
