/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { CargoHoldDimension } from "./cargoHoldDimension";
import type { CargoHoldContainerSize } from "./cargoHoldContainerSize";
import type { CargoHoldLimits } from "./cargoHoldLimits";

export interface CargoHold {
  dimensions: CargoHoldDimension;
  capacity: number;
  maxContainerSize: CargoHoldContainerSize;
  limits: CargoHoldLimits;
}
