/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { CelestialObjectMedia } from "./celestialObjectMedia";
import type { Starsystem } from "./starsystem";

export interface CelestialObject {
  name: string;
  slug: string;
  designation: string;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  type?: string | null;
  /** @nullable */
  habitable?: boolean | null;
  /** @nullable */
  fairchanceact?: boolean | null;
  /** @nullable */
  subType?: string | null;
  /** @nullable */
  size?: string | null;
  /** @nullable */
  danger?: number | null;
  /** @nullable */
  economy?: number | null;
  /** @nullable */
  population?: number | null;
  /** @nullable */
  locationLabel?: string | null;
  media: CelestialObjectMedia;
  starsystem: Starsystem;
  parent?: CelestialObject;
  moons?: CelestialObject[];
  createdAt: string;
  updatedAt: string;
  /** @deprecated */
  storeImage?: string;
  /** @deprecated */
  storeImageLarge?: string;
  /** @deprecated */
  storeImageMedium?: string;
  /** @deprecated */
  storeImageSmall?: string;
  id?: string;
}
