/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ShopCommodity } from "./shopCommodity";

export type CommodityAvailability = {
  listedAt: ShopCommodity[];
  boughtAt: ShopCommodity[];
  soldAt: ShopCommodity[];
};
