/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type CommodityTypeEnum =
  (typeof CommodityTypeEnum)[keyof typeof CommodityTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CommodityTypeEnum = {
  gas: "gas",
  metal: "metal",
  mineral: "mineral",
  non_metals: "non_metals",
  agricultural_supply: "agricultural_supply",
  food: "food",
  medical_supply: "medical_supply",
  processed_goods: "processed_goods",
  waste: "waste",
  scrap: "scrap",
  vice: "vice",
  harvestable: "harvestable",
  consumer_goods: "consumer_goods",
} as const;
