/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ComponentItemClassEnum } from "./componentItemClassEnum";
import type { ComponentAvailability } from "./componentAvailability";
import type { Manufacturer } from "./manufacturer";
import type { ComponentMedia } from "./componentMedia";
import type { ComponentTypeData } from "./componentTypeData";
import type { Hardpoint } from "./hardpoint";

export interface Component {
  id: string;
  name: string;
  slug: string;
  scKey?: string;
  scRef?: string;
  hidden: boolean;
  category?: string;
  type?: string;
  subType?: string;
  inventoryConsumption?: string;
  grade?: string;
  gradeLabel?: string;
  size?: string;
  itemClass?: ComponentItemClassEnum;
  itemClassLabel?: string;
  availability: ComponentAvailability;
  manufacturer?: Manufacturer;
  media: ComponentMedia;
  typeData?: ComponentTypeData;
  hardpoints?: Hardpoint[];
  createdAt: string;
  updatedAt: string;
}
