/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { MediaFile } from './MediaFile';

export type ComponentMedia = {
  storeImage?: MediaFile;
};
