/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ComponentQuantumDrive } from './ComponentQuantumDrive';
import type { CargoHold } from './CargoHold';
import type { FuelTank } from './FuelTank';
import type { ComponentThruster } from './ComponentThruster';

export type ComponentTypeData = ComponentQuantumDrive | CargoHold | FuelTank | ComponentThruster;
