/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ComponentQuantumDriveJump } from "./componentQuantumDriveJump";

export interface ComponentQuantumDrive {
  fuelRate: number;
  jumpRange: number;
  standardJump: ComponentQuantumDriveJump;
  splineJump: ComponentQuantumDriveJump;
}
