/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export interface ComponentQuantumDriveJump {
  speed: number;
  stage1AccelerationRate: number;
  stage2AccelerationRate: number;
  spoolUpTime: number;
  cooldown: number;
}
