/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { DockShipSizeEnum } from './DockShipSizeEnum';
import type { DockTypeEnum } from './DockTypeEnum';

export interface Dock {
  name: string;
  group?: string;
  size: DockShipSizeEnum;
  sizeLabel: string;
  type: DockTypeEnum;
  typeLabel: string;
}
