/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ItemPrice } from "./itemPrice";

export type EquipmentAvailability = {
  boughtAt: ItemPrice[];
  soldAt: ItemPrice[];
};
