/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type FleetMembershipStatusEnum =
  (typeof FleetMembershipStatusEnum)[keyof typeof FleetMembershipStatusEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FleetMembershipStatusEnum = {
  created: "created",
  invited: "invited",
  requested: "requested",
  accepted: "accepted",
  declined: "declined",
} as const;
