/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export interface Gallery {
  id: string;
  type: string;
  name: string;
  slug: string;
}
