/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type HardpointGroupEnum = typeof HardpointGroupEnum[keyof typeof HardpointGroupEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardpointGroupEnum = {
  avionic: 'avionic',
  system: 'system',
  propulsion: 'propulsion',
  thruster: 'thruster',
  weapon: 'weapon',
  defense: 'defense',
  auxiliary: 'auxiliary',
  seat: 'seat',
  relay: 'relay',
  other: 'other',
  unknown: 'unknown',
} as const;
