/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { HardpointGroupEnum } from "./hardpointGroupEnum";
import type { HardpointCategoryEnum } from "./hardpointCategoryEnum";
import type { HardpointSourceEnum } from "./hardpointSourceEnum";
import type { Component } from "./component";

export interface Hardpoint {
  id: string;
  group?: HardpointGroupEnum;
  groupKey?: string;
  matrixKey?: string;
  category?: HardpointCategoryEnum;
  name: string;
  minSize?: number;
  maxSize?: number;
  source?: HardpointSourceEnum;
  types?: string[];
  details?: string;
  component?: Component;
  hardpoints?: Hardpoint[];
  createdAt: string;
  updatedAt: string;
}
