/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export interface ImageQuery {
  galleryIdEq?: string;
  galleryTypeEq?: string;
}
