/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { GalleryTypeEnum } from "./galleryTypeEnum";

export interface ImageInputCreate {
  caption?: string;
  enabled?: boolean;
  global?: boolean;
  background?: boolean;
  galleryId?: string;
  galleryType?: GalleryTypeEnum;
  file?: string;
}
