/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ImportTypeEnum } from "./importTypeEnum";

export interface ImportQuery {
  typeEq?: ImportTypeEnum;
  typeIn?: ImportTypeEnum[];
}
