/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ItemPriceItemTypeEnum } from './ItemPriceItemTypeEnum';
import type { ItemPriceTypeEnum } from './ItemPriceTypeEnum';

export interface ItemPriceQuery {
  locationCont?: string;
  itemIdEq?: string;
  itemIdIn?: string[];
  itemTypeEq?: ItemPriceItemTypeEnum;
  itemTypeIn?: ItemPriceItemTypeEnum[];
  priceTypeEq?: ItemPriceTypeEnum;
  priceTypeIn?: ItemPriceTypeEnum[];
}
