/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ItemPriceTimeRangeEnum } from "./itemPriceTimeRangeEnum";
import type { ItemPriceTypeEnum } from "./itemPriceTypeEnum";
import type { ItemPriceItemTypeEnum } from "./itemPriceItemTypeEnum";

export interface ItemPrice {
  id: string;
  price: number;
  timeRange?: ItemPriceTimeRangeEnum;
  priceType: ItemPriceTypeEnum;
  itemId: string;
  itemType: ItemPriceItemTypeEnum;
  location: string;
  locationUrl?: string;
  createdAt: string;
  updatedAt: string;
}
