/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export interface ManufacturerQuery {
  withModels?: boolean;
  logoBlank?: boolean;
  nameEq?: string;
  nameCont?: string;
  nameIn?: string[];
  slugEq?: string;
  slugCont?: string;
  slugIn?: string[];
}
