/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ModelPaintQuerySorts } from "./modelPaintQuerySorts";

export interface ModelPaintQuery {
  nameEq?: string;
  nameCont?: string;
  idEq?: string;
  nameIn?: string[];
  idIn?: string[];
  idNotIn?: string[];
  modelSlugIn?: string[];
  modelSlugEq?: string;
  sorts?: ModelPaintQuerySorts;
}
