/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { MediaFile } from './MediaFile';

export type ModelPaintMedia = {
  angledView?: MediaFile;
  fleetchartImage?: string;
  sideView?: MediaFile;
  storeImage?: MediaFile;
  topView?: MediaFile;
  angledViewColored?: MediaFile;
  frontView?: MediaFile;
  frontViewColored?: MediaFile;
  sideViewColored?: MediaFile;
  rsiStoreImage?: MediaFile;
  topViewColored?: MediaFile;
};
