/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { Meta } from "./meta";
import type { ModelPaint } from "./modelPaint";

export interface ModelPaints {
  meta: Meta;
  items: ModelPaint[];
}
