/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ViewImage } from "./viewImage";
import type { MediaImage } from "./mediaImage";

export type ModelPaintMedia = {
  angledView?: ViewImage;
  fleetchartImage?: string;
  sideView?: ViewImage;
  storeImage?: ViewImage;
  topView?: ViewImage;
  angledViewColored?: ViewImage;
  frontView?: ViewImage;
  frontViewColored?: ViewImage;
  sideViewColored?: ViewImage;
  rsiStoreImage?: MediaImage;
  topViewColored?: ViewImage;
};
