/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type ModelSortEnum = (typeof ModelSortEnum)[keyof typeof ModelSortEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelSortEnum = {
  name_asc: "name asc",
  name_desc: "name desc",
  created_at_asc: "created_at asc",
  created_at_desc: "created_at desc",
  length_asc: "length asc",
  length_desc: "length desc",
  beam_asc: "beam asc",
  beam_desc: "beam desc",
  height_asc: "height asc",
  height_desc: "height desc",
  mass_asc: "mass asc",
  mass_desc: "mass desc",
  cargo_asc: "cargo asc",
  cargo_desc: "cargo desc",
  manufacturer_name_asc: "manufacturer_name asc",
  manufacturer_name_desc: "manufacturer_name desc",
  pledge_price_asc: "pledge_price asc",
  pledge_price_desc: "pledge_price desc",
  price_asc: "price asc",
  price_desc: "price desc",
  scm_speed_asc: "scm_speed asc",
  scm_speed_desc: "scm_speed desc",
  max_speed_asc: "max_speed asc",
  max_speed_desc: "max_speed desc",
  ground_max_speed_asc: "ground_max_speed asc",
  ground_max_speed_desc: "ground_max_speed desc",
  production_status_asc: "production_status asc",
  production_status_desc: "production_status desc",
  focus_asc: "focus asc",
  focus_desc: "focus desc",
} as const;
