/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type ModelHardpointTypeEnum = typeof ModelHardpointTypeEnum[keyof typeof ModelHardpointTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelHardpointTypeEnum = {
  radar: 'radar',
  computers: 'computers',
  fuel_intakes: 'fuel_intakes',
  fuel_tanks: 'fuel_tanks',
  jump_modules: 'jump_modules',
  quantum_fuel_tanks: 'quantum_fuel_tanks',
  power_plants: 'power_plants',
  coolers: 'coolers',
  shield_generators: 'shield_generators',
  quantum_drives: 'quantum_drives',
  main_thrusters: 'main_thrusters',
  maneuvering_thrusters: 'maneuvering_thrusters',
  weapons: 'weapons',
  turrets: 'turrets',
  missiles: 'missiles',
  qed: 'qed',
  emp: 'emp',
  utility_items: 'utility_items',
} as const;
