/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ModelQuerySorts } from "./modelQuerySorts";

export interface ModelQuery {
  nameCont?: string;
  idEq?: string;
  nameIn?: string[];
  idIn?: string[];
  idNotIn?: string[];
  manufacturerIn?: string[];
  productionStatusIn?: string[];
  searchCont?: string;
  scIdentifierBlank?: boolean;
  fleetchartImageBlank?: boolean;
  holoBlank?: boolean;
  topViewColoredBlank?: boolean;
  frontViewBlank?: boolean;
  sorts?: ModelQuerySorts;
}
