/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ViewImage } from './ViewImage';

export type ModelModuleMedia = {
  storeImage?: ViewImage;
};
