/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ViewImage } from "./viewImage";
import type { MediaImage } from "./mediaImage";

export type ModelModulePackageMedia = {
  angledView?: ViewImage;
  sideView?: ViewImage;
  storeImage?: MediaImage;
  topView?: ViewImage;
};
