/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { ModelAvailability } from './ModelAvailability';
import type { ModelCrew } from './ModelCrew';
import type { ModelLinks } from './ModelLinks';
import type { ModelLoaner } from './ModelLoaner';
import type { Manufacturer } from './Manufacturer';
import type { ModelMedia } from './ModelMedia';
import type { ModelMetrics } from './ModelMetrics';
import type { CargoHold } from './CargoHold';
import type { FuelTank } from './FuelTank';
import type { ModelProductionStatusEnum } from './ModelProductionStatusEnum';
import type { ModelSpeeds } from './ModelSpeeds';

export interface Model {
  id: string;
  scIdentifier?: string;
  name: string;
  slug: string;
  availability: ModelAvailability;
  brochure?: string;
  classification?: string;
  classificationLabel?: string;
  crew: ModelCrew;
  description?: string;
  erkulIdentifier?: string;
  focus?: string;
  hasImages: boolean;
  hasModules: boolean;
  hasPaints: boolean;
  hasUpgrades: boolean;
  hasVideos: boolean;
  holo?: string;
  lastPledgePrice?: number;
  lastPledgePriceLabel?: string;
  lastUpdatedAt?: string;
  lastUpdatedAtLabel?: string;
  links: ModelLinks;
  loaners: ModelLoaner[];
  manufacturer?: Manufacturer;
  media: ModelMedia;
  metrics: ModelMetrics;
  cargoHolds?: CargoHold[];
  hydrogenFuelTanks?: FuelTank[];
  quantumFuelTanks?: FuelTank[];
  onSale: boolean;
  pledgePrice?: number;
  pledgePriceLabel?: string;
  price?: number;
  priceLabel?: string;
  productionNote?: string;
  productionStatus?: ModelProductionStatusEnum;
  rsiId?: number;
  rsiName?: string;
  rsiSlug?: string;
  speeds: ModelSpeeds;
  createdAt: string;
  updatedAt: string;
  hidden: boolean;
  active: boolean;
  scLength?: number;
  scBeam?: number;
  scHeight?: number;
}
