/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type ModelHardpointCategoryEnum = typeof ModelHardpointCategoryEnum[keyof typeof ModelHardpointCategoryEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelHardpointCategoryEnum = {
  main: 'main',
  retro: 'retro',
  vtol: 'vtol',
  fixed: 'fixed',
  gimbal: 'gimbal',
  joint: 'joint',
  manned_turret: 'manned_turret',
  remote_turret: 'remote_turret',
  missile_turret: 'missile_turret',
  missile_rack: 'missile_rack',
  qed: 'qed',
  emp: 'emp',
} as const;
