/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { PageParameterParameter } from './PageParameterParameter';
import type { SortingParameterParameter } from './SortingParameterParameter';
import type { ModelQuery } from './ModelQuery';

export type ModelsParams = {
page?: PageParameterParameter;
perPage?: string;
/**
 * Sorting
 */
s?: SortingParameterParameter;
q?: ModelQuery;
};
