/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { PaginationPerPageStepsItem } from "./paginationPerPageStepsItem";

export interface Pagination {
  totalCount?: number;
  currentPage: number;
  totalPages: number;
  defaultPerPage?: number;
  maxPerPage?: number;
  perPageSteps?: PaginationPerPageStepsItem[];
}
