/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type StationSortEnum =
  (typeof StationSortEnum)[keyof typeof StationSortEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StationSortEnum = {
  name_asc: "name asc",
  name_desc: "name desc",
  station_type_asc: "station_type asc",
  station_type_desc: "station_type desc",
} as const;
