/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export interface Stats {
  onlineCount: number;
  shipsCountYear: number;
  shipsCountTotal: number;
  usersCountTotal: number;
  fleetsCountTotal: number;
}
