/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */

export type StationSizeEnum =
  (typeof StationSizeEnum)[keyof typeof StationSizeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StationSizeEnum = {
  small: "small",
  medium: "medium",
  large: "large",
} as const;
