/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { Meta } from './Meta';
import type { User } from './User';

export interface Users {
  meta: Meta;
  items: User[];
}
