/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { UserQuerySorts } from './UserQuerySorts';

export interface UserQuery {
  searchCont?: string;
  usernameCont?: string;
  usernameEq?: string;
  emailCont?: string;
  rsiHandleCont?: string;
  idIn?: string[];
  usernameIn?: string[];
  emailIn?: string[];
  rsihandleIn?: string[];
  sorts?: UserQuerySorts;
}
