/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { PageParameterParameter } from './PageParameterParameter';
import type { SortingParameterParameter } from './SortingParameterParameter';
import type { UserQuery } from './UserQuery';

export type UsersParams = {
page?: PageParameterParameter;
perPage?: string;
/**
 * Sorting
 */
s?: SortingParameterParameter;
q?: UserQuery;
cacheId?: string;
};
