/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net Command API
 * OpenAPI spec version: v1
 */
import type { VehicleQuerySorts } from './VehicleQuerySorts';

export interface VehicleQuery {
  searchCont?: string;
  idEq?: string;
  idIn?: string[];
  idNotIn?: string[];
  nameCont?: string;
  nameIn?: string[];
  userUsernameIn?: string[];
  modelSlugIn?: string[];
  manufacturerIn?: string[];
  modelIdEq?: string;
  modelIdIn?: string[];
  modelIdNotIn?: string[];
  modelNameCont?: string;
  modelNameIn?: string[];
  modelProductionStatusIn?: string[];
  modelSearchCont?: string;
  loanerEq?: boolean;
  wantedEq?: boolean;
  sorts?: VehicleQuerySorts;
}
