export default () => ({
  ships: [],
  detailsVisible: false,
  filterVisible: true,
  fleetchartVisible: false,
  fleetchartZoomData: null,
  fleetchartViewpoint: 'side',
  fleetchartLabels: false,
  fleetchartScreenHeight: '1x',
  preview: true,
  money: true,
  starterGuideVisible: false,
  perPage: 30,
  gridView: true,
})
