export default () => ({
  ships: [],
  detailsVisible: false,
  filterVisible: true,
  fleetchartVisible: false,
  fleetchartScale: 100,
  fleetchartViewpoint: 'side',
  fleetchartLabels: false,
  publicFleetchartVisible: false,
  publicFleetchartScale: 100,
  publicFleetchartViewpoint: 'side',
  publicFleetchartLabels: false,
  preview: true,
  money: true,
  starterGuideVisible: false,
  perPage: 30,
  gridView: true,
})
