/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type BoughtViaEnum = typeof BoughtViaEnum[keyof typeof BoughtViaEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BoughtViaEnum = {
  pledge_store: 'pledge_store',
  ingame: 'ingame',
} as const;
