/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { CargoHoldDimension } from './CargoHoldDimension';
import type { CargoHoldContainerSize } from './CargoHoldContainerSize';
import type { CargoHoldLimits } from './CargoHoldLimits';

export interface CargoHold {
  dimensions: CargoHoldDimension;
  capacity: number;
  maxContainerSize: CargoHoldContainerSize;
  limits: CargoHoldLimits;
}
