/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { CelestialObjectSortEnum } from "./celestialObjectSortEnum";

export type CelestialObjectQuerySorts =
  | CelestialObjectSortEnum[]
  | CelestialObjectSortEnum;
