/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type CelestialObjectSortEnum =
  (typeof CelestialObjectSortEnum)[keyof typeof CelestialObjectSortEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CelestialObjectSortEnum = {
  name_asc: "name asc",
  name_desc: "name desc",
  parent_id_asc: "parent_id asc",
  parent_id_desc: "parent_id desc",
  designation_asc: "designation asc",
  designation_desc: "designation desc",
} as const;
