/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { CommodityQuery } from "./commodityQuery";

export type CommoditiesParams = {
  page?: string;
  perPage?: string;
  q?: CommodityQuery;
  cacheId?: string;
};
