/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Meta } from './Meta';
import type { Component } from './Component';

export interface Components {
  meta: Meta;
  items: Component[];
}
