/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ItemPrice } from "./itemPrice";

export type ComponentAvailability = {
  boughtAt: ItemPrice[];
  soldAt: ItemPrice[];
};
