/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface ComponentQuery {
  nameCont?: string;
  idIn?: string[];
  nameIn?: string[];
  itemTypeIn?: string[];
  componentClassIn?: string[];
}
