/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ThrusterClassEnum } from './ThrusterClassEnum';

export interface ComponentThruster {
  thrustCapacity?: number;
  thrusterType: string;
  thrusterClass?: ThrusterClassEnum;
  fuelBurnRatePer10KNewton: number;
}
