/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ComponentQuery } from "./componentQuery";

export type ComponentsParams = {
  page?: string;
  perPage?: string;
  q?: ComponentQuery;
  cacheId?: string;
};
