/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface DockCount {
  count: number;
  size: string;
  type: string;
  typeLabel: string;
}
