/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type DockTypeEnum = typeof DockTypeEnum[keyof typeof DockTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DockTypeEnum = {
  vehiclepad: 'vehiclepad',
  garage: 'garage',
  landingpad: 'landingpad',
  dockingport: 'dockingport',
  hangar: 'hangar',
} as const;
