/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { EquipmentAvailability } from './EquipmentAvailability';
import type { Manufacturer } from './Manufacturer';
import type { EquipmentMedia } from './EquipmentMedia';

export interface Equipment {
  id: string;
  name: string;
  slug: string;
  availability: EquipmentAvailability;
  backpackCompatibility?: string;
  coreCompatibility?: string;
  damageReduction?: string;
  description?: string;
  extras?: string;
  grade?: string;
  itemType?: string;
  itemTypeLabel?: string;
  manufacturer?: Manufacturer;
  media: EquipmentMedia;
  range?: string;
  rateOfFire?: string;
  size?: string;
  slot?: string;
  slotLabel?: string;
  storage?: string;
  temperatureRating?: string;
  type?: string;
  typeLabel?: string;
  volume?: string;
  weaponClass?: string;
  weaponClassLabel?: string;
  createdAt: string;
  updatedAt: string;
}
