/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { EquipmentAvailability } from "./equipmentAvailability";
import type { Manufacturer } from "./manufacturer";
import type { EquipmentMedia } from "./equipmentMedia";

export interface Equipment {
  id: string;
  name: string;
  slug: string;
  availability: EquipmentAvailability;
  backpackCompatibility?: string;
  coreCompatibility?: string;
  damageReduction?: string;
  description?: string;
  extras?: string;
  grade?: string;
  itemType?: string;
  itemTypeLabel?: string;
  manufacturer?: Manufacturer;
  media: EquipmentMedia;
  range?: string;
  rateOfFire?: string;
  size?: string;
  slot?: string;
  slotLabel?: string;
  storage?: string;
  temperatureRating?: string;
  type?: string;
  typeLabel?: string;
  volume?: string;
  weaponClass?: string;
  weaponClassLabel?: string;
  createdAt: string;
  updatedAt: string;
  /** @deprecated */
  storeImage?: string;
  /** @deprecated */
  storeImageIsFallback?: boolean;
  /** @deprecated */
  storeImageLarge?: string;
  /** @deprecated */
  storeImageMedium?: string;
  /** @deprecated */
  storeImageSmall?: string;
}
