/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { FleetVehicleQuerySorts } from "./fleetVehicleQuerySorts";

export interface FleetVehicleQuery {
  beamGteq?: number;
  beamLteq?: number;
  classificationIn?: string[];
  focusIn?: string[];
  heightGteq?: number;
  heightLteq?: number;
  lengthGteq?: number;
  lengthLteq?: number;
  manufacturerIn?: string[];
  onSaleEq?: boolean;
  pledgePriceGteq?: number;
  pledgePriceLteq?: number;
  pledgePriceIn?: number[];
  priceGteq?: number;
  priceLteq?: number;
  priceIn?: number[];
  productionStatusIn?: string[];
  searchCont?: string;
  sizeIn?: string[];
  modelNameCont?: string;
  modelNameOrModelDescriptionCont?: string;
  loanerEq?: boolean;
  memberIn?: string[];
  sorts?: FleetVehicleQuerySorts;
}
