/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface FleetInviteUrlCreateInput {
  limit?: number;
  expiresAfterMinutes?: number;
}
