/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Model } from './Model';
import type { VehiclePublic } from './VehiclePublic';

export type FleetPublicVehiclesItemsItem = Model | VehiclePublic;
