/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Meta } from "./meta";
import type { FleetPublicVehiclesItemsItem } from "./fleetPublicVehiclesItemsItem";

export interface FleetPublicVehicles {
  meta: Meta;
  items: FleetPublicVehiclesItemsItem[];
}
