/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Model } from "./model";
import type { VehiclePublic } from "./vehiclePublic";

export type FleetVehiclesItemsItem = Model | VehiclePublic;
