/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface FleetInviteUrl {
  token: string;
  url: string;
  expiresAfter?: string;
  expiresAfterLabel?: string;
  expired?: boolean;
  limit?: number;
  limitReached?: boolean;
  createdAt: string;
  updatedAt: string;
}
