/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { FleetVehicleSortEnum } from './FleetVehicleSortEnum';

export type FleetVehicleQuerySorts = FleetVehicleSortEnum[] | FleetVehicleSortEnum;
