/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { FleetMembershipRoleEnum } from "./fleetMembershipRoleEnum";
import type { FleetMemberQuerySorts } from "./fleetMemberQuerySorts";

export interface FleetMemberQuery {
  usernameCont?: string;
  /**
   * Use usernameCont instead
   * @deprecated
   */
  nameCont?: string;
  roleIn?: FleetMembershipRoleEnum[];
  sorts?: FleetMemberQuerySorts;
}
