/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { FleetMemberQuery } from "./fleetMemberQuery";

export type FleetMembersParams = {
  page?: string;
  perPage?: string;
  q?: FleetMemberQuery;
  cacheId?: string;
};
