/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface FleetUpdateInput {
  fid?: string;
  name?: string;
  logo?: Blob;
  removeLogo?: boolean;
  backgroundImage?: Blob;
  removeBackground?: boolean;
  description?: string;
  publicFleet?: boolean;
  publicFleetStats?: boolean;
  homepage?: string;
  rsiSid?: string;
  discord?: string;
  ts?: string;
  youtube?: string;
  twitch?: string;
  guilded?: string;
}
