/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface FleetRoleExtended {
  id: string;
  name: string;
  slug: string;
  rank: string;
  permanent: boolean;
  resourceAccess: string[];
  createdAt: string;
  updatedAt: string;
}
