/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Meta } from './Meta';
import type { FleetVehiclesItemsItem } from './FleetVehiclesItemsItem';

export interface FleetVehicles {
  meta: Meta;
  items: FleetVehiclesItemsItem[];
}
