/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Meta } from './Meta';
import type { FleetPublicVehiclesItemsItem } from './FleetPublicVehiclesItemsItem';

export interface FleetPublicVehicles {
  meta: Meta;
  items: FleetPublicVehiclesItemsItem[];
}
