/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { HangarQuery } from "./hangarQuery";

export type GetParams = {
  page?: string;
  perPage?: string;
  q?: HangarQuery;
};
