/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { HangarQuery } from './HangarQuery';

export type GetParams = {
page?: string;
perPage?: string;
q?: HangarQuery;
};
