/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type HabitationTypeEnum =
  (typeof HabitationTypeEnum)[keyof typeof HabitationTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HabitationTypeEnum = {
  container: "container",
  small_apartment: "small_apartment",
  medium_apartment: "medium_apartment",
  large_apartment: "large_apartment",
  suite: "suite",
} as const;
