/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Meta } from "./meta";
import type { Vehicle } from "./vehicle";

export interface Hangar {
  meta: Meta;
  items: Vehicle[];
}
