/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { HangarClassificationMetric } from './HangarClassificationMetric';
import type { HangarGroupMetric } from './HangarGroupMetric';

export interface HangarStatsPublic {
  total: number;
  classifications: HangarClassificationMetric[];
  groups: HangarGroupMetric[];
}
