/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface HangarGroupCreateInput {
  name: string;
  color: string;
  /** @nullable */
  sort?: number | null;
  /** @nullable */
  public?: boolean | null;
}
