/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { HangarClassificationMetric } from "./hangarClassificationMetric";
import type { HangarGroupMetric } from "./hangarGroupMetric";

export interface HangarStatsPublic {
  total: number;
  classifications: HangarClassificationMetric[];
  groups: HangarGroupMetric[];
}
