/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface HangarGroup {
  id: string;
  name: string;
  slug: string;
  color: string;
  public: boolean;
  sort?: number;
  vehiclesCount?: number;
  createdAt: string;
  updatedAt: string;
}
