/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { HangarClassificationMetric } from './HangarClassificationMetric';
import type { HangarGroupMetric } from './HangarGroupMetric';
import type { HangarMetrics } from './HangarMetrics';

export interface HangarStats {
  total: number;
  wishlistTotal: number;
  classifications: HangarClassificationMetric[];
  groups: HangarGroupMetric[];
  metrics: HangarMetrics;
}
