/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type HardpointSourceEnum =
  (typeof HardpointSourceEnum)[keyof typeof HardpointSourceEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardpointSourceEnum = {
  ship_matrix: "ship_matrix",
  game_files: "game_files",
} as const;
