/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum HardpointCategoryEnum {
    RADAR = 'radar',
    COMPUTERS = 'computers',
    SCANNERS = 'scanners',
    POWERPLANT = 'powerplant',
    COOLER = 'cooler',
    SHIELDGENERATOR = 'shieldgenerator',
    MODULE = 'module',
    SALVAGEFILLERSTATION = 'salvagefillerstation',
    FUELTANKS = 'fueltanks',
    FUEL_INTAKES = 'fuel_intakes',
    QUANTUMDRIVE = 'quantumdrive',
    JUMPDRIVE = 'jumpdrive',
    MAIN_THRUSTERS = 'main_thrusters',
    MANEUVERING_THRUSTERS = 'maneuvering_thrusters',
    WEAPONS = 'weapons',
    WEAPON_MOUNTS = 'weapon_mounts',
    TURRET = 'turret',
    MISSILE_RACKS = 'missile_racks',
    BOMBCOMPARTMENTS = 'bombcompartments',
    QUANTUMENFORCEMENTDEVICE = 'quantumenforcementdevice',
    EMP = 'emp',
    SALVAGEMUNCHING = 'salvagemunching',
    ARMOR = 'armor',
    COUNTERMEASURES = 'countermeasures',
    SELFDESTRUCT = 'selfdestruct',
    LIFESUPPORT = 'lifesupport',
    BATTERIES = 'batteries',
    UTILITY = 'utility',
    SEAT = 'seat',
    RELAY = 'relay',
    PAINTS = 'paints',
    DOORS = 'doors',
    CARGOGRID = 'cargogrid',
    INVENTORY = 'inventory',
    CONTROLLER = 'controller',
    UNKNOWN = 'unknown',
}
