/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type HardpointCategoryEnum =
  (typeof HardpointCategoryEnum)[keyof typeof HardpointCategoryEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HardpointCategoryEnum = {
  radar: "radar",
  computers: "computers",
  scanners: "scanners",
  powerplant: "powerplant",
  cooler: "cooler",
  shieldgenerator: "shieldgenerator",
  module: "module",
  salvagefillerstation: "salvagefillerstation",
  fueltanks: "fueltanks",
  fuel_intakes: "fuel_intakes",
  quantumdrive: "quantumdrive",
  jumpdrive: "jumpdrive",
  main_thrusters: "main_thrusters",
  retro_thrusters: "retro_thrusters",
  vtol_thrusters: "vtol_thrusters",
  maneuvering_thrusters: "maneuvering_thrusters",
  weapons: "weapons",
  weapon_mounts: "weapon_mounts",
  turret: "turret",
  missile_racks: "missile_racks",
  bombcompartments: "bombcompartments",
  quantumenforcementdevice: "quantumenforcementdevice",
  emp: "emp",
  salvagemunching: "salvagemunching",
  armor: "armor",
  countermeasures: "countermeasures",
  selfdestruct: "selfdestruct",
  lifesupport: "lifesupport",
  batteries: "batteries",
  utility: "utility",
  seat: "seat",
  relay: "relay",
  paints: "paints",
  doors: "doors",
  cargogrid: "cargogrid",
  inventory: "inventory",
  controller: "controller",
  unknown: "unknown",
} as const;
