/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Gallery } from "./gallery";

export interface Image {
  id: string;
  background: boolean;
  bigUrl: string;
  caption?: string;
  name: string;
  smallUrl: string;
  type: string;
  url: string;
  width?: number;
  height?: number;
  gallery?: Gallery;
  createdAt: string;
  updatedAt: string;
}
