/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Gallery } from './Gallery';

export interface Image {
  name: string;
  contentType: string;
  size: number;
  url: string;
  smallUrl?: string;
  mediumUrl?: string;
  largeUrl?: string;
  xlargeUrl?: string;
  width?: number;
  height?: number;
  uploadedAt: string;
  id: string;
  background: boolean;
  caption?: string;
  gallery?: Gallery;
  createdAt: string;
  updatedAt: string;
}
