/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ImageQuery } from './ImageQuery';

export type ImagesParams = {
page?: string;
perPage?: string;
q?: ImageQuery;
cacheId?: string;
};
