/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ImportStatusEnum = typeof ImportStatusEnum[keyof typeof ImportStatusEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImportStatusEnum = {
  created: 'created',
  started: 'started',
  finished: 'finished',
  failed: 'failed',
} as const;
