/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ItemPriceTypeEnum =
  (typeof ItemPriceTypeEnum)[keyof typeof ItemPriceTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemPriceTypeEnum = {
  buy: "buy",
  sell: "sell",
  rental: "rental",
} as const;
