/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ItemPriceTimeRangeEnum =
  (typeof ItemPriceTimeRangeEnum)[keyof typeof ItemPriceTimeRangeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ItemPriceTimeRangeEnum = {
  "1-day": "1-day",
  "3-days": "3-days",
  "7-days": "7-days",
  "30-days": "30-days",
} as const;
