/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ManufacturerQuery } from './ManufacturerQuery';

export type ManufacturersParams = {
page?: string;
perPage?: string;
q?: ManufacturerQuery;
cacheId?: string;
};
