/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface Manufacturer {
  name: string;
  slug: string;
  code?: string;
  logo?: string;
  longName?: string;
  scRef?: string;
  createdAt: string;
  updatedAt: string;
}
