/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface MediaImage {
  large: string;
  medium: string;
  small: string;
  source: string;
}
