/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ModelCrew = {
  max?: number;
  maxLabel?: string;
  min?: number;
  minLabel?: string;
};
