/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ModelModuleMetrics } from "./modelModuleMetrics";
import type { CargoHold } from "./cargoHold";
import type { ModelModuleAvailability } from "./modelModuleAvailability";
import type { ModelModuleMedia } from "./modelModuleMedia";
import type { Manufacturer } from "./manufacturer";
import type { Hardpoint } from "./hardpoint";

export interface ModelModule {
  id: string;
  name: string;
  slug?: string;
  description?: string;
  scKey?: string;
  metrics?: ModelModuleMetrics;
  cargoHolds?: CargoHold[];
  availability: ModelModuleAvailability;
  media: ModelModuleMedia;
  pledgePrice?: number;
  productionStatus?: string;
  manufacturer?: Manufacturer;
  hardpoints?: Hardpoint[];
  createdAt: string;
  updatedAt: string;
}
