/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ViewImage } from "./viewImage";
import type { MediaImage } from "./mediaImage";

export type ModelExtendedMedia = {
  angledView?: ViewImage;
  angledViewColored?: ViewImage;
  fleetchartImage?: string;
  frontView?: ViewImage;
  frontViewColored?: ViewImage;
  sideView?: ViewImage;
  sideViewColored?: ViewImage;
  storeImage?: MediaImage;
  topView?: ViewImage;
  topViewColored?: ViewImage;
};
