/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ModelQuerySorts } from "./modelQuerySorts";

export interface ModelQuery {
  beamGteq?: number;
  beamLteq?: number;
  classificationIn?: string[];
  descriptionCont?: string;
  focusIn?: string[];
  heightGteq?: number;
  heightLteq?: number;
  idIn?: string[];
  idNotIn?: string[];
  lengthGteq?: number;
  lengthLteq?: number;
  manufacturerIn?: string[];
  nameCont?: string;
  nameEq?: string;
  slugEq?: string;
  nameIn?: string[];
  slugIn?: string[];
  nameOrDescriptionCont?: string;
  onSaleEq?: boolean;
  pledgePriceGteq?: number;
  pledgePriceLteq?: number;
  pledgePriceIn?: number[];
  priceGteq?: number;
  priceLteq?: number;
  priceIn?: number[];
  productionStatusIn?: string[];
  searchCont?: string;
  sizeIn?: string[];
  willItFit?: string;
  withCargo?: boolean;
  sorts?: ModelQuerySorts;
}
