/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ModelHardpointGroupEnum =
  (typeof ModelHardpointGroupEnum)[keyof typeof ModelHardpointGroupEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ModelHardpointGroupEnum = {
  avionic: "avionic",
  system: "system",
  propulsion: "propulsion",
  thruster: "thruster",
  weapon: "weapon",
} as const;
