/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Meta } from "./meta";
import type { ModelModulePackage } from "./modelModulePackage";

export interface ModelModulePackages {
  meta: Meta;
  items: ModelModulePackage[];
}
