/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ModelExtendedSpeeds = {
  groundAcceleration?: number;
  groundDecceleration?: number;
  groundMaxSpeed?: number;
  groundReverseSpeed?: number;
  maxSpeed?: number;
  pitch?: number;
  pitchBoosted?: number;
  roll?: number;
  rollBoosted?: number;
  scmSpeed?: number;
  scmSpeedBoosted?: number;
  reverseSpeedBoosted?: number;
  yaw?: number;
  yawBoosted?: number;
};
