/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ModelExtendedAvailability } from './ModelExtendedAvailability';
import type { ModelExtendedCrew } from './ModelExtendedCrew';
import type { ModelExtendedLinks } from './ModelExtendedLinks';
import type { ModelLoaner } from './ModelLoaner';
import type { Manufacturer } from './Manufacturer';
import type { ModelExtendedMedia } from './ModelExtendedMedia';
import type { ModelExtendedMetrics } from './ModelExtendedMetrics';
import type { CargoHold } from './CargoHold';
import type { FuelTank } from './FuelTank';
import type { ModelProductionStatusEnum } from './ModelProductionStatusEnum';
import type { ModelExtendedSpeeds } from './ModelExtendedSpeeds';
import type { DockCount } from './DockCount';

export interface ModelExtended {
  id: string;
  scIdentifier?: string;
  name: string;
  slug: string;
  availability: ModelExtendedAvailability;
  brochure?: string;
  classification?: string;
  classificationLabel?: string;
  crew: ModelExtendedCrew;
  description?: string;
  erkulIdentifier?: string;
  focus?: string;
  hasImages: boolean;
  hasModules: boolean;
  hasPaints: boolean;
  hasUpgrades: boolean;
  hasVideos: boolean;
  holo?: string;
  lastPledgePrice?: number;
  lastPledgePriceLabel?: string;
  lastUpdatedAt?: string;
  lastUpdatedAtLabel?: string;
  links: ModelExtendedLinks;
  loaners: ModelLoaner[];
  manufacturer?: Manufacturer;
  media: ModelExtendedMedia;
  metrics: ModelExtendedMetrics;
  cargoHolds?: CargoHold[];
  hydrogenFuelTanks?: FuelTank[];
  quantumFuelTanks?: FuelTank[];
  onSale: boolean;
  pledgePrice?: number;
  pledgePriceLabel?: string;
  price?: number;
  priceLabel?: string;
  productionNote?: string;
  productionStatus?: ModelProductionStatusEnum;
  rsiId?: number;
  rsiName?: string;
  rsiSlug?: string;
  speeds: ModelExtendedSpeeds;
  createdAt: string;
  updatedAt: string;
  dockCounts: DockCount[];
}
