/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Hardpoint } from "./hardpoint";
import type { ModelHardpoint } from "./modelHardpoint";

export type ModelHardpoints200Item = Hardpoint | ModelHardpoint;
