/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface ModelPaintQuery {
  nameCont?: string;
  idEq?: string;
  modelSlugEq?: string;
  idIn?: string[];
  idNotIn?: string[];
  nameIn?: string[];
}
