/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ModelQuery } from './ModelQuery';

export type ModelsParams = {
page?: string;
perPage?: string;
q?: ModelQuery;
cacheId?: string;
};
