/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Hardpoint } from './Hardpoint';
import type { ModelHardpoint } from './ModelHardpoint';

export type ModelHardpoints200Item = Hardpoint | ModelHardpoint;
