/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ViewImage } from "./viewImage";

export type ModelModulePackageMedia = {
  angledView?: ViewImage;
  sideView?: ViewImage;
  storeImage?: ViewImage;
  topView?: ViewImage;
};
