/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ModelAvailability } from "./modelAvailability";
import type { ModelCrew } from "./modelCrew";
import type { ModelLinks } from "./modelLinks";
import type { ModelLoaner } from "./modelLoaner";
import type { Manufacturer } from "./manufacturer";
import type { ModelMedia } from "./modelMedia";
import type { ModelMetrics } from "./modelMetrics";
import type { CargoHold } from "./cargoHold";
import type { FuelTank } from "./fuelTank";
import type { ModelProductionStatusEnum } from "./modelProductionStatusEnum";
import type { ModelSpeeds } from "./modelSpeeds";

export interface Model {
  id: string;
  scIdentifier?: string;
  name: string;
  slug: string;
  availability: ModelAvailability;
  brochure?: string;
  classification?: string;
  classificationLabel?: string;
  crew: ModelCrew;
  description?: string;
  erkulIdentifier?: string;
  focus?: string;
  hasImages: boolean;
  hasModules: boolean;
  hasPaints: boolean;
  hasUpgrades: boolean;
  hasVideos: boolean;
  holo?: string;
  lastPledgePrice?: number;
  lastPledgePriceLabel?: string;
  lastUpdatedAt?: string;
  lastUpdatedAtLabel?: string;
  links: ModelLinks;
  loaners: ModelLoaner[];
  manufacturer?: Manufacturer;
  media: ModelMedia;
  metrics: ModelMetrics;
  cargoHolds?: CargoHold[];
  hydrogenFuelTanks?: FuelTank[];
  quantumFuelTanks?: FuelTank[];
  onSale: boolean;
  pledgePrice?: number;
  pledgePriceLabel?: string;
  price?: number;
  priceLabel?: string;
  productionNote?: string;
  productionStatus?: ModelProductionStatusEnum;
  rsiId?: number;
  rsiName?: string;
  rsiSlug?: string;
  speeds: ModelSpeeds;
  createdAt: string;
  updatedAt: string;
}
