/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ModelPaintQuery } from './ModelPaintQuery';

export type PaintsParams = {
page?: string;
perPage?: string;
q?: ModelPaintQuery;
};
