/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { FleetVehicleQuery } from "./fleetVehicleQuery";

export type PublicFleetVehiclesParams = {
  page?: string;
  perPage?: string;
  q?: FleetVehicleQuery;
  grouped?: boolean;
  cacheId?: string;
};
