/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { RoadmapWeekQuery } from "./roadmapWeekQuery";

export interface RoadmapWeek {
  value: number;
  query: RoadmapWeekQuery;
  label: string;
}
