/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { RsiHangarItemKindEnum } from './RsiHangarItemKindEnum';

export interface RsiHangarItemInput {
  id: string;
  name: string;
  /** @nullable */
  customName?: string | null;
  type: RsiHangarItemKindEnum;
}
