/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type SearchResultTypeEnum =
  (typeof SearchResultTypeEnum)[keyof typeof SearchResultTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SearchResultTypeEnum = {
  Model: "Model",
  Component: "Component",
  Shop: "Shop",
  Station: "Station",
  CelestialObject: "CelestialObject",
  Starsystem: "Starsystem",
  Equipment: "Equipment",
  Commodity: "Commodity",
} as const;
