/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Model } from "./model";
import type { Component } from "./component";
import type { Commodity } from "./commodity";
import type { Equipment } from "./equipment";
import type { ModelModule } from "./modelModule";
import type { ModelPaint } from "./modelPaint";
import type { Shop } from "./shop";
import type { Station } from "./station";
import type { CelestialObject } from "./celestialObject";
import type { Starsystem } from "./starsystem";

export type SearchResultItem =
  | Model
  | Component
  | Commodity
  | Equipment
  | ModelModule
  | ModelPaint
  | Shop
  | Station
  | CelestialObject
  | Starsystem;
