/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface SessionInput {
  /** Username or email */
  login?: string;
  password?: string;
  rememberMe?: boolean;
  twoFactorCode?: string;
}
