/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ShopCommodityQuery } from "./shopCommodityQuery";
import type { ShopCommodityOrderQuery } from "./shopCommodityOrderQuery";

export type ShopCommoditiesParams = {
  page?: string;
  perPage?: string;
  search?: string;
  query?: ShopCommodityQuery;
  order?: ShopCommodityOrderQuery;
  cacheId?: string;
};
