/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface ShopQuery {
  searchCont?: string;
  nameCont?: string;
  commodityNameCont?: string;
  nameIn?: string[];
  modelIn?: string[];
  equipmentIn?: string[];
  componentIn?: string[];
  commodityIn?: string[];
  shopTypeIn?: string[];
  commodityCategoryIn?: string[];
  stationIn?: string[];
  celestialObjectIn?: string[];
  starsystemIn?: string[];
}
