/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ShopCommodityItemTypeEnum =
  (typeof ShopCommodityItemTypeEnum)[keyof typeof ShopCommodityItemTypeEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShopCommodityItemTypeEnum = {
  Model: "Model",
  Equipment: "Equipment",
  Commodity: "Commodity",
  Component: "Component",
  ModelModule: "ModelModule",
  ModelPaint: "ModelPaint",
} as const;
