/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface ShopCommodityQuery {
  priceGteq?: number;
  priceLteq?: number;
  name?: string[];
  manufacturerSlug?: string[];
  category?: string[];
  subCategory?: string[];
}
