/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type ShopCommodityCategoryEnum =
  (typeof ShopCommodityCategoryEnum)[keyof typeof ShopCommodityCategoryEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ShopCommodityCategoryEnum = {
  model: "model",
  equipment: "equipment",
  commodity: "commodity",
  component: "component",
  modelmodule: "modelmodule",
  modelpaint: "modelpaint",
} as const;
