/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { Model } from "./model";
import type { Component } from "./component";
import type { Commodity } from "./commodity";
import type { Equipment } from "./equipment";
import type { ModelModule } from "./modelModule";
import type { ModelPaint } from "./modelPaint";

export type ShopCommodityItem =
  | Model
  | Component
  | Commodity
  | Equipment
  | ModelModule
  | ModelPaint;
