/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { ComponentClassEnum } from "./componentClassEnum";
import type { EquipmentTypeEnum } from "./equipmentTypeEnum";
import type { CommodityTypeEnum } from "./commodityTypeEnum";

export type ShopCommoditySubCategory =
  | string
  | ComponentClassEnum
  | EquipmentTypeEnum
  | CommodityTypeEnum;
