/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { StationQuery } from "./stationQuery";

export type StationsParams = {
  page?: string;
  perPage?: string;
  q?: StationQuery;
  cacheId?: string;
};
