/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type StationClassificationEnum =
  (typeof StationClassificationEnum)[keyof typeof StationClassificationEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const StationClassificationEnum = {
  city: "city",
  trading: "trading",
  mining: "mining",
  salvaging: "salvaging",
  farming: "farming",
  science: "science",
  security: "security",
  rest_stop: "rest_stop",
  settlement: "settlement",
  town: "town",
  drug_lab: "drug_lab",
  cargo: "cargo",
  derelict: "derelict",
  prison: "prison",
  spaceport: "spaceport",
} as const;
