/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { StationTypeEnum } from "./stationTypeEnum";
import type { StationSizeEnum } from "./stationSizeEnum";
import type { StationClassificationEnum } from "./stationClassificationEnum";
import type { DockCount } from "./dockCount";
import type { HabitationCount } from "./habitationCount";
import type { StationMedia } from "./stationMedia";
import type { CelestialObject } from "./celestialObject";
import type { Starsystem } from "./starsystem";
import type { Shop } from "./shop";
import type { Dock } from "./dock";
import type { Habitation } from "./habitation";

export interface Station {
  name: string;
  slug: string;
  cargoHub: boolean;
  type: StationTypeEnum;
  typeLabel: string;
  size: StationSizeEnum;
  sizeLabel: string;
  classification: StationClassificationEnum;
  classificationLabel: string;
  description?: string;
  dockCounts?: DockCount[];
  habitable: boolean;
  habitationCounts?: HabitationCount[];
  hasImages: boolean;
  locationLabel?: string;
  location?: string;
  media: StationMedia;
  refinery: boolean;
  shopListLabel?: string;
  celestialObject: CelestialObject;
  starsystem?: Starsystem;
  shops?: Shop[];
  docks?: Dock[];
  habitations?: Habitation[];
  createdAt: string;
  updatedAt: string;
  /** @deprecated */
  backgroundImage?: string;
  /** @deprecated */
  storeImage?: string;
  /** @deprecated */
  storeImageLarge?: string;
  /** @deprecated */
  storeImageMedium?: string;
  /** @deprecated */
  storeImageSmall?: string;
}
