/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface UserCreateInput {
  username?: string;
  email?: string;
  password?: string;
  passwordConfirmation?: string;
  saleNotify?: boolean;
  fleetInviteToken?: string;
}
