/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface UserUpdateInput {
  avatar?: string;
  removeAvatar?: boolean;
  rsiHandle?: string;
  homepage?: string;
  discord?: string;
  youtube?: string;
  guilded?: string;
  twitch?: string;
  saleNotify?: boolean;
  publicHangar?: boolean;
  publicHangarLoaners?: boolean;
  publicWishlist?: boolean;
  hideOwner?: boolean;
}
