/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
export enum VehicleSortEnum {
    FLAGSHIP_DESC = 'flagship desc',
    FLAGSHIP_ASC = 'flagship asc',
    NAME_ASC = 'name asc',
    NAME_DESC = 'name desc',
    MODEL_NAME_ASC = 'model_name asc',
    MODEL_NAME_DESC = 'model_name desc',
    CREATED_AT_ASC = 'created_at asc',
    CREATED_AT_DESC = 'created_at desc',
    UPDATED_AT_ASC = 'updated_at asc',
    UPDATED_AT_DESC = 'updated_at desc',
    MODEL_MANUFACTURER_NAME_ASC = 'model_manufacturer_name asc',
    MODEL_MANUFACTURER_NAME_DESC = 'model_manufacturer_name desc',
    MODEL_LENGTH_ASC = 'model_length asc',
    MODEL_LENGTH_DESC = 'model_length desc',
    MODEL_BEAM_ASC = 'model_beam asc',
    MODEL_BEAM_DESC = 'model_beam desc',
    MODEL_HEIGHT_ASC = 'model_height asc',
    MODEL_HEIGHT_DESC = 'model_height desc',
    MODEL_MASS_ASC = 'model_mass asc',
    MODEL_MASS_DESC = 'model_mass desc',
    MODEL_CARGO_ASC = 'model_cargo asc',
    MODEL_CARGO_DESC = 'model_cargo desc',
    MODEL_PLEDGE_PRICE_ASC = 'model_pledge_price asc',
    MODEL_PLEDGE_PRICE_DESC = 'model_pledge_price desc',
    MODEL_PRICE_ASC = 'model_price asc',
    MODEL_PRICE_DESC = 'model_price desc',
    MODEL_SCM_SPEED_ASC = 'model_scm_speed asc',
    MODEL_SCM_SPEED_DESC = 'model_scm_speed desc',
    MODEL_MAX_SPEED_ASC = 'model_max_speed asc',
    MODEL_MAX_SPEED_DESC = 'model_max_speed desc',
    MODEL_GROUND_MAX_SPEED_ASC = 'model_ground_max_speed asc',
    MODEL_GROUND_MAX_SPEED_DESC = 'model_ground_max_speed desc',
    MODEL_PRODUCTION_STATUS_ASC = 'model_production_status asc',
    MODEL_PRODUCTION_STATUS_DESC = 'model_production_status desc',
    MODEL_FOCUS_ASC = 'model_focus asc',
    MODEL_FOCUS_DESC = 'model_focus desc',
}
