/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { BoughtViaEnum } from './BoughtViaEnum';
import type { HangarGroup } from './HangarGroup';
import type { Model } from './Model';
import type { ModelModulePackage } from './ModelModulePackage';
import type { ModelPaint } from './ModelPaint';
import type { ModelUpgrade } from './ModelUpgrade';

export interface Vehicle {
  id: string;
  name?: string;
  slug?: string;
  serial?: string;
  alternativeNames: string[];
  boughtVia: BoughtViaEnum;
  boughtViaLabel?: string;
  flagship: boolean;
  hangarGroupIds: string[];
  hangarGroups: HangarGroup[];
  loaner: boolean;
  model: Model;
  modelModuleIds: string[];
  modelUpgradeIds: string[];
  modulePackage?: ModelModulePackage;
  nameVisible: boolean;
  paint?: ModelPaint;
  public: boolean;
  saleNotify: boolean;
  upgrade?: ModelUpgrade;
  wanted: boolean;
  createdAt: string;
  updatedAt: string;
}
