/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export interface VehicleExport {
  name: string;
  slug: string;
  shipCode?: string;
  manufacturerName: string;
  manufacturerCode?: string;
  paintSlug?: string;
  shipName?: string;
  shipSerial?: string;
  wanted: boolean;
  flagship: boolean;
  public: boolean;
  saleNotify: boolean;
  nameVisible: boolean;
  groups: string[];
  modules: string[];
  upgrades: string[];
}
