/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { BoughtViaEnum } from "./boughtViaEnum";

export interface VehicleCreateInput {
  modelId: string;
  /** @nullable */
  name?: string | null;
  /** @nullable */
  serial?: string | null;
  /** @nullable */
  wanted?: boolean | null;
  /** @nullable */
  nameVisible?: boolean | null;
  /** @nullable */
  public?: boolean | null;
  /** @nullable */
  saleNotify?: boolean | null;
  /** @nullable */
  flagship?: boolean | null;
  /** @nullable */
  modelPaintId?: string | null;
  /** @nullable */
  boughtVia?: BoughtViaEnum;
  /** @nullable */
  hangarGroupIds?: string[] | null;
  /** @nullable */
  modelModuleIds?: string[] | null;
  /** @nullable */
  modelUpgradeIds?: string[] | null;
  /** @nullable */
  alternativeNames?: string[] | null;
}
