/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */

export type VehicleSortEnum =
  (typeof VehicleSortEnum)[keyof typeof VehicleSortEnum];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const VehicleSortEnum = {
  flagship_desc: "flagship desc",
  flagship_asc: "flagship asc",
  name_asc: "name asc",
  name_desc: "name desc",
  model_name_asc: "model_name asc",
  model_name_desc: "model_name desc",
  created_at_asc: "created_at asc",
  created_at_desc: "created_at desc",
  updated_at_asc: "updated_at asc",
  updated_at_desc: "updated_at desc",
  model_manufacturer_name_asc: "model_manufacturer_name asc",
  model_manufacturer_name_desc: "model_manufacturer_name desc",
  model_length_asc: "model_length asc",
  model_length_desc: "model_length desc",
  model_beam_asc: "model_beam asc",
  model_beam_desc: "model_beam desc",
  model_height_asc: "model_height asc",
  model_height_desc: "model_height desc",
  model_mass_asc: "model_mass asc",
  model_mass_desc: "model_mass desc",
  model_cargo_asc: "model_cargo asc",
  model_cargo_desc: "model_cargo desc",
  model_pledge_price_asc: "model_pledge_price asc",
  model_pledge_price_desc: "model_pledge_price desc",
  model_price_asc: "model_price asc",
  model_price_desc: "model_price desc",
  model_scm_speed_asc: "model_scm_speed asc",
  model_scm_speed_desc: "model_scm_speed desc",
  model_max_speed_asc: "model_max_speed asc",
  model_max_speed_desc: "model_max_speed desc",
  model_ground_max_speed_asc: "model_ground_max_speed asc",
  model_ground_max_speed_desc: "model_ground_max_speed desc",
  model_production_status_asc: "model_production_status asc",
  model_production_status_desc: "model_production_status desc",
  model_focus_asc: "model_focus asc",
  model_focus_desc: "model_focus desc",
} as const;
