/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import type { VideoTypeEnum } from "./videoTypeEnum";

export interface Video {
  id: string;
  type: VideoTypeEnum;
  url: string;
  videoId: string;
  createdAt: string;
  updatedAt: string;
}
