## Planets [/v1/planets]

### GET List [GET]
Get a List of Planets

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
            ]
