## Planet [/v1/planets/{slug}]

### GET Detail [GET]
Get Detail of a Planet referenced by its Slug

+ Parameters

    + slug: `crusader` (required, string) - The Planet Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            {
            }
