## Station [/v1/stations/{slug}]

### GET Detail [GET]
Get Detail of a Station referenced by its Slug

+ Parameters

    + slug: `port-olisar` (required, string) - The Station Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            {
            }
