production:
  push_api_key: "<%= Rails.application.credentials.dig(:appsignal, :push_api_key) rescue nil %>"
  name: "Fleetyards"
  active: true
  working_directory_path: "/tmp/appsignal"
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError
      - ActionController::InvalidAuthenticityToken
      - ActionDispatch::Http::MimeNegotiation::InvalidType
      - ActionController::BadRequest
      - ActionDispatch::Http::Parameters::ParseError

staging:
  push_api_key: "<%= Rails.application.credentials.dig(:appsignal, :push_api_key) rescue nil %>"
  name: "fleetyards"
  active: true
  working_directory_path: "/tmp/appsignal"
  log_level: "debug"
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError
      - ActionController::InvalidAuthenticityToken
      - ActionDispatch::Http::MimeNegotiation::InvalidType
      - ActionController::BadRequest
      - ActionDispatch::Http::Parameters::ParseError

development:
  active: false
