production:
  push_api_key: "<%= Rails.application.credentials.dig(:appsignal, :push_api_key) rescue nil %>"
  name: "Fleetyards"
  active: true
  working_directory_path: "/tmp/appsignal"
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError
      - ActionController::InvalidAuthenticityToken

staging:
  push_api_key: "<%= Rails.application.credentials.dig(:appsignal, :push_api_key) rescue nil %>"
  name: "Fleetyards"
  active: true
  working_directory_path: "/tmp/appsignal"
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError
      - ActionController::InvalidAuthenticityToken

development:
  active: false
