production:
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Fleetyards"
  active: true
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError
      - ActionController::InvalidAuthenticityToken

staging:
  push_api_key: "<%= ENV['APPSIGNAL_PUSH_API_KEY'] %>"
  name: "Fleetyards"
  active: true
  ignore_errors:
      - ActiveRecord::RecordNotFound
      - ActionController::RoutingError
      - ActionController::InvalidAuthenticityToken

development:
  active: false
