production: &default
  adapter: redis
  url: <%= Rails.configuration.redis.url %>
  channel_prefix: fleetyards_<%= Rails.env %>

staging:
  <<: *default

ci:
  <<: *default

development:
  <<: *default

test:
  adapter: test
