production: &default
  database: <%= ENV["DB_NAME"] || 'fleetyards' %>
  adapter: postgresql
  host: <%= ENV["DB_HOST"] || 'localhost' %>
  port: <%= ENV["DB_PORT"] || 8271 %>
  user: <%= ENV["DB_USER"] || 'root' %>
  password: <%= ENV["DB_PASSWORD"] || 'password' %>
  pool: <%= ENV.fetch("DB_POOL_SIZE") { Integer(ENV.fetch("MAX_THREADS", 5)) * 2 } %>

staging:
  <<: *default

ci:
  <<: *default

development:
  <<: *default
  database: <%= ENV["DB_NAME"] || "fleetyards_dev#{ENV['WORKTREE_SUFFIX']}" %>

test:
  <<: *default
  database: <%= ENV["DB_NAME"] || "fleetyards_test#{ENV['WORKTREE_SUFFIX']}#{ENV['TEST_ENV_NUMBER']}" %>
