## Ship [/v1/ships/{slug}]

### GET List [GET]
Get a List of Ships

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
                {
                    "id": "4a624dcc-5e61-4166-822a-2d918edc5910",
                    "name": "300i",
                    "slug": "300i",
                    "description": "If you're going to travel the stars... why not do it in style? The 300i is Origin Jumpworks' premiere luxury spacecraft. It is a sleek, silver killer that sends as much of a message with its silhouette as it does with its weaponry.",
                    "length": "24.000",
                    "beam": "16.000",
                    "height": "7.000",
                    "mass": "200",
                    "cargo": "4",
                    "netCargo": null,
                    "crew": "1",
                    "storeImage": "http://api.fleetyards.dev/uploads/ship/store_image/4a624dcc-5e61-4166-822a-2d918edc5910/300i_storefront_visual.jpg",
                    "storeUrl": "https://robertsspaceindustries.com/pledge/ships/origin-300/300i",
                    "price": "53.21",
                    "onSale": true,
                    "productionStatus": "flight-ready",
                    "productionNote": "Update Pass Scheduled",
                    "powerplantSize": 3,
                    "shieldSize": 3,
                    "classification": "personal_transport",
                    "focus": "Touring",
                    "rsiId": 7,
                    "manufacturer": {
                        "id": "4052e7cf-5451-4a9f-a7e2-797daa26ccd8",
                        "name": "Origin Jumpworks GmbH"
                    },
                    "shipRole": {
                        "id": "71f6ac9a-f0b0-4a2c-a2a2-77c3f2a8b2bd",
                        "name": "Touring"
                    },
                    "createdAt": "2014-10-04T23:45:27+02:00",
                    "updatedAt": "2017-08-30T22:00:25+02:00"
                }
            ]
