## Detail [/v1/ships/{slug}]

+ Parameters

    + slug: `origin-600i-explorer` (required, string) - The Ship Slug

### GET Detail [GET]
Get Detail of a Ship referenced by its Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            {
                "id": "db264a17-16df-4ddb-81e2-27aa58b8d835",
                "name": "Origin 600i Explorer",
                "slug": "origin-600i-explorer",
                "description": "Let the voyage begin with the 2947 600i from Origin Jumpworks. This multi-role luxury vessel from Origin Jumpworks features an exquisitely detailed hull design that . \n\nThe 600i is designed with a cutting edge modular technology, allowing you to customize your ship for your needs. Taking the family on a long-distance trip across the stars? The Touring module lets your guests relax in ease with stunning furniture from some of the Empire's top designers. Looking to stamp your name in history with the discovery of a new star system? The 600i's Explorer module swaps the lounge for a robust scanning station as well as additional utility hardpoints to increase the ship's effectiveness even more.\n\nRegardless of where your journey takes you, the 600i guarantees that you'll get there fast and in style.",
                "length": "61.500",
                "beam": "43.000",
                "height": "18.500",
                "mass": "1887",
                "cargo": "36",
                "netCargo": "",
                "crew": "5",
                "storeImage": "http://api.fleetyards.dev/uploads/ship/store_image/db264a17-16df-4ddb-81e2-27aa58b8d835/600i-Exploration.jpg",
                "storeUrl": "https://robertsspaceindustries.com/pledge/ships/600i/Origin-600i-Explorer",
                "price": "0.0",
                "onSale": false,
                "productionStatus": "in-concept",
                "productionNote": null,
                "powerplantSize": null,
                "shieldSize": null,
                "classification": "personal_transport",
                "focus": "Exploration",
                "rsiId": 141,
                "manufacturer": {
                    "id": "4052e7cf-5451-4a9f-a7e2-797daa26ccd8",
                    "name": "Origin Jumpworks GmbH"
                },
                "shipRole": {
                    "id": "ef1a817f-ba95-4d40-8af6-9e7f07f54456",
                    "name": "Exploration"
                },
                "hardpoints": [
                    {
                        "id": "84bc725a-5ea4-4173-b908-384c11f1a1c4",
                        "name": "Main",
                        "hardpointClass": null,
                        "rating": 2,
                        "maxSize": null,
                        "quantity": null,
                        "categoryName": "Propulsion",
                        "categorySlug": "propulsion",
                        "component": {
                            "id": "31618bfa-9a80-4a85-a732-157d42e4fee5",
                            "name": "Coming Soon",
                            "size": "0",
                            "type": "shieldgenerator"
                        }
                    }
                ],
                "images": [
                    {
                        "id": "ae88e4ad-4b92-48dc-bcba-aa49f4f30438",
                        "name": "600i-Front-4thrids.png",
                        "url": "http://api.fleetyards.dev/uploads/image/name/ae88e4ad-4b92-48dc-bcba-aa49f4f30438/600i-Front-4thrids.png",
                        "type": "image/png",
                        "small": {
                            "url": "http://api.fleetyards.dev/uploads/image/name/ae88e4ad-4b92-48dc-bcba-aa49f4f30438/small_600i-Front-4thrids.png"
                        },
                        "big": {
                            "url": "http://api.fleetyards.dev/uploads/image/name/ae88e4ad-4b92-48dc-bcba-aa49f4f30438/big_600i-Front-4thrids.png"
                        },
                        "dark": {
                            "url": "http://api.fleetyards.dev/uploads/image/name/ae88e4ad-4b92-48dc-bcba-aa49f4f30438/dark_600i-Front-4thrids.png"
                        },
                        "createdAt": "2017-08-30T23:27:08+02:00",
                        "updatedAt": "2017-08-30T23:27:14+02:00"
                    }
                ],
                "videos": [
                    {
                        "id": "92efed26-43fc-443e-bd43-2a75bf43e6b5",
                        "url": "https://www.youtube.com/embed/gbCSQDhPOlk",
                        "type": "youtube",
                        "createdAt": "2017-09-07T21:37:51+02:00",
                        "updatedAt": "2017-09-07T21:37:51+02:00"
                    }
                ],
                "createdAt": "2017-08-30T22:01:40+02:00",
                "updatedAt": "2017-09-07T21:37:51+02:00"
            }
