### GET Latest [GET/v1/ships/latest]
Get the last 10 Ships ordered by ```updatedAt```

The Response Body is identical to ```/v1/ships```

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)
