import createPersistedState from 'vuex-persistedstate'

export default function getStorePlugins() {
  return [
    createPersistedState({
      key: 'FleetYards',
      paths: [
        'storeVersion',
        'app.navSlim',
        'session.authenticated',
        'session.accessConfirmed',
        'cookies.infoVisible',
        'cookies.cookies',
        'hangar.ships',
        'hangar.detailsVisible',
        'hangar.fleetchartScale',
        'hangar.fleetchartViewpoint',
        'hangar.fleetchartLabels',
        'hangar.publicFleetchartScale',
        'hangar.publicFleetchartViewpoint',
        'hangar.publicFleetchartLabels',
        'hangar.preview',
        'hangar.money',
        'hangar.starterGuideVisible',
        'hangar.perPage',
        'hangar.gridView',
        'models.detailsVisible',
        'models.fleetchartScale',
        'models.fleetchartViewpoint',
        'models.fleetchartLabels',
        'models.holoviewerVisible',
        'search.history',
        'fleet.detailsVisible',
        'fleet.fleetchartScale',
        'fleet.fleetchartViewpoint',
        'fleet.fleetchartLabels',
        'fleet.publicFleetchartScale',
        'fleet.publicFleetchartViewpoint',
        'fleet.publicFleetchartLabels',
        'fleet.grouped',
        'fleet.money',
        'fleet.preview',
        'fleet.inviteToken',
        'shoppingCart.items',
      ],
    }),
  ]
}
