/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * FleetYards.net API
 * OpenAPI spec version: v1
 */
import { useQuery } from "@tanstack/vue-query";
import type {
  DataTag,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from "@tanstack/vue-query";

import { unref } from "vue";
import type { MaybeRef } from "vue";

import type { ModelPaint, PaintsParams } from "../models";

import { axiosClient } from "../axiosClient";
import type { ErrorType } from "../axiosClient";
import { customQueryOptions } from "../../customQueryOptions";

/**
 * @summary Model Paints List
 */
export const paints = (
  params?: MaybeRef<PaintsParams>,
  signal?: AbortSignal,
) => {
  params = unref(params);

  return axiosClient<ModelPaint[]>({
    url: `/model-paints`,
    method: "GET",
    params: unref(params),
    signal,
  });
};

export const getPaintsQueryKey = (params?: MaybeRef<PaintsParams>) => {
  return ["model-paints", ...(params ? [params] : [])] as const;
};

export const usePaintsQueryOptions = <
  TData = Awaited<ReturnType<typeof paints>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<PaintsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paints>>, TError, TData>
    >;
  },
) => {
  const { query: queryOptions } = options ?? {};

  const queryKey = getPaintsQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof paints>>> = ({
    signal,
  }) => paints(params, signal);

  const customOptions = customQueryOptions({
    ...queryOptions,
    queryKey,
    queryFn,
  });

  return customOptions as UseQueryOptions<
    Awaited<ReturnType<typeof paints>>,
    TError,
    TData
  >;
};

export type PaintsQueryResult = NonNullable<Awaited<ReturnType<typeof paints>>>;
export type PaintsQueryError = ErrorType<unknown>;

/**
 * @summary Model Paints List
 */

export function usePaints<
  TData = Awaited<ReturnType<typeof paints>>,
  TError = ErrorType<unknown>,
>(
  params?: MaybeRef<PaintsParams>,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof paints>>, TError, TData>
    >;
  },
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData> } {
  const queryOptions = usePaintsQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData>;
  };

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData>;

  return query;
}
