shared:
  name: <%= ENV["APP_NAME"] || 'Fleetyards.net' %>
  copyright_owner: <%= ENV["COPYRIGHT_OWNER"] || 'Torlek Maru' %>

  api_version: <%= ENV["API_VERSION"] || 'v1' %>
  admin_api_version: <%= ENV["ADMIN_API_VERSION"] || 'v1' %>
  store_version: <%= ENV["APP_STORE_VERSION"] || 11.0 %>
  embed_store_version: <%= ENV["APP_EMBED_STORE_VERSION"] || 2.0 %>

  domain: <%= ENV["DOMAIN"] || "localhost:#{ENV["PORT"] || 3000}" %>
  short_domain: <%= ENV["SHORT_DOMAIN"] %>
  cookie_domain: <%= ENV["COOKIE_DOMAIN"] || :all %>
  cookie_prefix: <%= ENV["COOKIE_PREFIX"] || 'FLTYRD' %>

  on_subdomain?: <%= ENV["ON_SUBDOMAIN"] || false %>

  cable_endpoint: <%= ENV["CABLE_ENDPOINT"] || "ws://localhost:#{ENV["PORT"]}/cable" %>
  mailer_default_from: <%= ENV["MAILER_DEFAULT_FROM"] || "info@fleetyards.net" %>
  cdn_endpoint: <%= ENV["CDN_ENDPOINT"] || "cdn.fltyrd.net" %>
  storage_cdn_endpoint: <%= ENV["STORAGE_CDN_ENDPOINT"] %>

  github_repo: <%= ENV["GITHUB_REPO"] || 'fleetyards/fleetyards' %>

  discord:
    oauth_client_id: <%= Rails.app.creds.option(:discord, :oauth_client_id) %>
    oauth_secret: <%= Rails.app.creds.option(:discord, :oauth_secret) %>

  github:
    oauth_client_id: <%= Rails.app.creds.option(:github, :oauth_client_id) %>
    oauth_secret: <%= Rails.app.creds.option(:github, :oauth_secret) %>

  twitch:
    oauth_client_id: <%= Rails.app.creds.option(:twitch, :oauth_client_id) %>
    oauth_secret: <%= Rails.app.creds.option(:twitch, :oauth_secret) %>

  google:
    oauth_client_id: <%= Rails.app.creds.option(:google, :oauth_client_id) %>
    oauth_secret: <%= Rails.app.creds.option(:google, :oauth_secret) %>

  bluesky:
    client_id: <%= Rails.app.creds.option(:bluesky, :client_id) %>

  citizenid:
    oauth_client_id: <%= Rails.app.creds.option(:citizenid, :oauth_client_id) %>
    issuer: <%= ENV["CITIZENID__ISSUER"] || "https://citizenid.dev/" %>

staging:
  on_subdomain?: true

production:
  on_subdomain?: true

  citizenid:
    issuer: <%= ENV["CITIZEN_ID_ISSUER"] || "https://citizenid.space/" %>

  cdn_endpoint: <%= ENV["CDN_ENDPOINT"] || "https://cdn.fltyrd.net" %>
  legacy_cdn_endpoint: <%= ENV["LEGACY_CDN_ENDPOINT"] || "https://cdn.fleetyards.net" %>
