shared:
  name: <%= Rails.application.credentials.dig(:maintainer, :name) %>
  mail: <%= Rails.application.credentials.dig(:maintainer, :mail) %>

  address:
    street: <%= Rails.application.credentials.dig(:maintainer, :address, :street) %>
    postalcode: <%= Rails.application.credentials.dig(:maintainer, :address, :postalcode) %>
    city: <%= Rails.application.credentials.dig(:maintainer, :address, :city) %>
    country: <%= Rails.application.credentials.dig(:maintainer, :address, :country) %>
