# frozen_string_literal: true

require "test_helper"

# Guards the MJML pipeline, across every mailer with a preview. Driven off
# ActionMailer::Preview so a new mailer is covered the moment it gets one,
# without this file being touched.
#
# Every assertion here stands for a failure that happened during the migration
# and was silent when it did - nothing raised, the mail just went out wrong:
#
# - An uncompiled template leaves literal <mj-text> in the delivered HTML.
#   mrml-rails compiles only the render carrying the <mjml> root, so a fragment
#   rendered outside layouts/mailer arrives as markup. MRML also passes tags it
#   does not recognise straight through, so a typo ships the same way.
# - A remote stylesheet link makes premailer fetch it over the network on every
#   delivery. mj-font emitted exactly that, which is why the layout has none.
# - The text part is generated by premailer, not by us, so dropping or
#   reconfiguring premailer-rails silently makes every mail HTML-only.
# - premailer drops the backdrop image, in two different ways, and strips the
#   border-radius off the element MJML puts the panel's frame on.
class MjmlRenderingTest < ActionMailer::TestCase
  MJML_LAYOUT = "mailer"

  # No records are created on purpose. Every preview falls back to an unsaved
  # stand-in when the database has nothing, so running on the empty database a
  # test case starts with is what proves that fallback works - which is the state
  # a fresh worktree and CI are both in. The real-record branch is the one a
  # development database exercises by hand.

  # DeviseMailerPreview previews Devise::Mailer, which the name does not give us.
  def self.mailer_for(preview)
    base = preview.name.sub(/Preview\z/, "")
    base.safe_constantize || base.sub(/Mailer\z/, "::Mailer").safe_constantize
  end

  def self.mjml_emails
    ActionMailer::Preview.all.flat_map do |preview|
      mailer = mailer_for(preview)
      next [] unless mailer.respond_to?(:_layout) && mailer._layout == MJML_LAYOUT

      preview.emails.map { |email| [preview, email] }
    end
  end

  test "at least one mailer is on the MJML layout" do
    refute_empty self.class.mjml_emails,
      "No preview resolves to a mailer using layout #{MJML_LAYOUT.inspect}. Either the " \
      "migration finished and this file should now assert against layouts/mailer, or " \
      "preview discovery broke and every assertion below is passing vacuously."
  end

  mjml_emails.each do |preview, email|
    test "#{preview.name}##{email} compiles to HTML with no MJML tags left" do
      html = html_part_for(preview, email)

      leaked = html.scan(/<\/?mj-[a-z-]+/).tally
      assert_empty leaked,
        "#{preview.name}##{email} still contains MJML tags after rendering: " \
        "#{leaked.inspect}. mrml-rails compiles only the render carrying the <mjml> " \
        "root, so this means the mailer is not on the #{MJML_LAYOUT.inspect} layout."
    end

    test "#{preview.name}##{email} references no remote stylesheet" do
      html = html_part_for(preview, email)

      remote = html.scan(/<link[^>]*rel=["']stylesheet["'][^>]*>/i)
        .select { |tag| tag.match?(%r{href=["']https?://}i) }

      assert_empty remote,
        "#{preview.name}##{email} links a remote stylesheet: #{remote.inspect}. " \
        "premailer resolves every stylesheet link it finds, so this puts a " \
        "third-party HTTP request on the path of every delivery."
    end

    test "#{preview.name}##{email} still ships a text part" do
      mail = delivered(preview, email)

      assert mail.multipart?, "#{preview.name}##{email} is not multipart"
      text = mail.parts.find { |part| part.content_type.to_s.start_with?("text/plain") }
      assert text, "#{preview.name}##{email} has no text/plain part"
      assert text.body.decoded.present?, "#{preview.name}##{email} has an empty text part"
    end

    # The backdrop reached the recipient as flat black twice during this
    # migration, both times silently: once because premailer reduced MJML's
    # background shorthand to one it could parse and dropped the url with it,
    # and once because its css_to_attributes pass moved the url into a legacy
    # attribute and deleted the declaration. Neither raised anything.
    test "#{preview.name}##{email} keeps the backdrop image in CSS" do
      html = html_part_for(preview, email)

      assert_match(/background-image:\s*url\(['"]?[^'")]*mail-bg[^'")]*['"]?\)/, html,
        "#{preview.name}##{email} has no background-image declaration for the backdrop. " \
        "premailer has dropped it before - check Premailer::Rails.config[:css_to_attributes] " \
        "is still false and that nothing reintroduced a `background:` shorthand on .mail-bg.")
    end

    # The panel's frame and its rounded corners have to stay on one element.
    # mj-wrapper's own `border` attribute puts the frame on the inner td while
    # the radius stays on the table, and then premailer drops the td's
    # border-radius - and a cell's radius is inert under border-collapse:
    # collapse regardless. That shipped a rounded fill inside a square frame.
    test "#{preview.name}##{email} rounds the panel frame" do
      html = html_part_for(preview, email)

      framed = html.scan(/<table[^>]*style="([^"]*border:\s*2px solid[^"]*)"/i).flatten
      assert_equal 1, framed.size,
        "expected exactly one table carrying the panel's 2px frame, found #{framed.size}"

      style = framed.first
      assert_match(/border-radius:\s*#{Regexp.escape(MailerTheme::RADIUS_SURFACE)}/o, style,
        "the panel's frame and its border-radius are on different elements again")
      assert_match(/border-collapse:\s*separate/, style,
        "border-radius on a table is inert under border-collapse: collapse")
    end

    test "#{preview.name}##{email} keeps the panel end-cap" do
      html = html_part_for(preview, email)

      assert_includes html.downcase, MailerTheme::ENDCAP,
        "#{preview.name}##{email} has no #{MailerTheme::ENDCAP} anywhere - the panel's " \
        "end-cap is the app's signature and it did not survive compilation."
    end
  end

  private

  # premailer generates the text part in its delivery hook, so the multipart
  # message only exists after the hook has run. Calling the hook directly keeps
  # this off the network: a real deliver_now would try to resolve asset hosts.
  def delivered(preview, email)
    mail = preview.call(email)
    Premailer::Rails::Hook.delivering_email(mail)
    mail
  end

  def html_part_for(preview, email)
    mail = delivered(preview, email)
    part = mail.parts.find { |p| p.content_type.to_s.start_with?("text/html") }
    assert part, "#{preview.name}##{email} has no text/html part"
    part.body.decoded
  end
end
