### GET Random [GET/v1/images/random]
Get 14 random Images

The Response Body is identical to ```/v1/images```

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)
