/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FleetYards.net OAuth API
 * OpenAPI spec version: v1
 */

export * from './OauthAuthorizationInput';
export * from './OauthAuthorizationRedirect';
export * from './OauthAuthorizationRedirectStatus';
export * from './OauthPreAuthorization';
export * from './OauthPreAuthorizationScopesItem';
export * from './OauthPreAuthorizeParams';
export * from './StandardError';