/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FleetYards.net OAuth API
 * OpenAPI spec version: v1
 */

export type OauthPreAuthorizationScopesItem = {
  name: string;
  description: string;
};
