/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FleetYards.net OAuth API
 * OpenAPI spec version: v1
 */

export type OauthAuthorizationRedirectStatus = typeof OauthAuthorizationRedirectStatus[keyof typeof OauthAuthorizationRedirectStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const OauthAuthorizationRedirectStatus = {
  redirect: 'redirect',
  post: 'post',
} as const;
