/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * FleetYards.net OAuth API
 * OpenAPI spec version: v1
 */

export interface OauthAuthorizationInput {
  clientId: string;
  redirectUri: string;
  responseType: string;
  /** @nullable */
  responseMode?: string | null;
  scope: string;
  /** @nullable */
  state?: string | null;
  /** @nullable */
  codeChallenge?: string | null;
  /** @nullable */
  codeChallengeMethod?: string | null;
}
