name: JS Setup Job
description: JS Setup Tasks
runs:
  using: "composite"
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: "lts/*"
    - name: Install pnpm
      run: npm install -g pnpm@10.31.0
      shell: bash
    - uses: actions/cache@v5
      with:
        path: |
          "**/node_modules"
          "~/.pnpm-store"
        key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}
    - run: pnpm install
      shell: bash
