## Starsystems [/v1/starsystems]

### GET List [GET]
Get a List of Starsystems

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            [
            ]
