## Starsystem [/v1/starsystems/{slug}]

### GET Detail [GET]
Get Detail of a Starsystem referenced by its Slug

+ Parameters

    + slug: `stanton` (required, string) - The Starsystem Slug

+ Request (application/json)

    + Headers

            Accept: application/json



+ Response 200 (application/json; charset=utf-8)

    + Body
    
            {
            }
