export default () => ({
  detailsVisible: false,
  filterVisible: true,
  fleetchartVisible: false,
  fleetchartScale: 100,
  fleetchartViewpoint: 'side',
  fleetchartLabels: false,
  publicFleetchartScale: 100,
  publicFleetchartViewpoint: 'side',
  publicFleetchartLabels: false,
  grouped: true,
  money: true,
  preview: true,
  inviteToken: null,
})
