

name: Api Schema Check Job

on:
  workflow_call:

jobs:
  api-schema-lint:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DOMAIN: fleetyards.test
      ON_SUBDOMAIN: true
      DATABASE_URL: postgresql://root:root@127.0.0.1:5432/fleetyards_test
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: root
      OPENSEARCH_URL: http://localhost:8273

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_DB: fleetyards_test
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6.2.10-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: ./.github/workflows/js-setup-action
      - run: mkdir -p log
      - run: |
          ./bin/generate-schema
          git diff --exit-code ./swagger/**/schema.yaml
        shell: bash
