

name: Api Schema Check Job

on:
  workflow_call:

jobs:
  api-schema-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/workflows/js-setup-action
      - run: |
          ./bin/generate-schema
          git diff --exit-code ./swagger/v2/swagger.yaml
        shell: bash
