

name: Api Schema Check Job

on:
  workflow_call:

jobs:
  api-schema-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: ./.github/workflows/js-setup-action
      - run: |
          ./bin/generate-schema
          git diff --exit-code ./swagger/**/schema.yaml
        shell: bash
