name: Deploy Job

on:
  workflow_call:
    inputs:
      capEnv:
        required: true
        type: string
      name:
        required: true
        type: string
      url:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    environment:
      name: ${{ inputs.name }}
      url: ${{ inputs.url }}

    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}
          if_key_exists: ignore
      - name: Deploy
        run: bundle exec cap ${{ inputs.capEnv }} deploy
