name: E2E Job

on:
  workflow_call:

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.60.0-noble
    strategy:
      fail-fast: false
      matrix:
        shardIndex: [1, 2]
        shardTotal: [2]
    env:
      RAILS_ENV: test
      NODE_OPTIONS: "--max_old_space_size=4096"
      DATABASE_URL: postgresql://root:password@postgres:5432/fleetyards_test
      DATABASE_HOST: postgres
      DATABASE_USER: root
      DATABASE_PASSWORD: password
      REDIS_URL: redis://redis:6379
      RAILS_SERVE_STATIC_FILES: 1
      DISABLE_DATABASE_ENVIRONMENT_CHECK: 1
      DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true
      TEST_SEEDS: 1
      JOBS: 1
      PORT: 8280

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_DB: fleetyards_test
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:6.2.10-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: apt-get update && apt-get install -y --no-install-recommends libyaml-dev libvips-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - uses: ./.github/workflows/js-setup-action
      - run: mkdir -p log && mkdir -p tmp/pids && rm -f tmp/pids/*
      - name: Setup DB
        run: bundle exec rails db:create db:schema:load
      - name: Assets Compile
        run: bundle exec rails assets:precompile
      - name: Prefill DB
        run: bundle exec rails db:seed
      - name: Run e2e Tests
        run: pnpm test:e2e:run --shard=${{ matrix.shardIndex }}/${{ matrix.shardTotal }}
      - uses: actions/upload-artifact@v7
        if: always()
        with:
          name: blob-report-${{ matrix.shardIndex }}-attempt-${{ github.run_attempt }}
          path: blob-report
          retention-days: 1

  merge-reports:
    # Merge reports after playwright-tests, even if some shards have failed
    if: ${{ !cancelled() }}
    needs: [e2e-test]

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: ./.github/workflows/js-setup-action

      - name: Download blob reports from GitHub Actions Artifacts
        uses: actions/download-artifact@v8
        with:
          path: all-blob-reports
          pattern: blob-report-*
          merge-multiple: true

      - name: Merge into HTML Report
        run: pnpm playwright merge-reports --reporter html ./all-blob-reports

      - name: Upload HTML report
        uses: actions/upload-artifact@v7
        with:
          name: html-report--attempt-${{ github.run_attempt }}
          path: playwright-report
          retention-days: 2
