name: Lint translations

on:
  push:
    branches: ["l10n_main"]
  workflow_dispatch:

jobs:
  js-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/js-setup-action

  js-lint-fix:
    needs: js-setup
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/js-setup-action
      - run: yarn run lint:fix
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: lint translations"
          add: "app/frontend/translations/*"
