name: Main

on:
  push:
    branches: ["main", "staging", "trying"]
    tags-ignore:
      - "*.*"
    paths-ignore:
      - "CHANGELOG.md"
      - "config/version.rb"
      - "package.json"
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  js-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/workflows/js-setup-action

  ruby-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

  js-lint:
    needs: js-setup
    uses: ./.github/workflows/js-lint.job.yml

  tsc:
    needs: [ruby-setup, js-setup]
    uses: ./.github/workflows/tsc.job.yml

  js-prettier:
    needs: js-setup
    uses: ./.github/workflows/js-prettier.job.yml

  api-schema-lint:
    name: API Schema Lint
    needs: js-setup
    uses: ./.github/workflows/api-schema-lint.job.yml

  js-tests:
    needs: js-setup
    uses: ./.github/workflows/js-tests.job.yml

  ruby-lint:
    needs: ruby-setup
    uses: ./.github/workflows/ruby-lint.job.yml

  ruby-tests:
    needs: ruby-setup
    uses: ./.github/workflows/ruby-tests.job.yml

  seeds:
    needs: ruby-setup
    uses: ./.github/workflows/seeds.job.yml

  build:
    if: (github.event_name == 'push' && github.ref == 'refs/heads/main') || github.event_name == 'workflow_dispatch'
    uses: ./.github/workflows/build.job.yml
    with:
      tag: ${{ github.ref_name }}
    secrets: inherit
    permissions:
      contents: read
      packages: write

  api-schema-breaking:
    name: API Schema Breaking Changes
    uses: ./.github/workflows/api-schema-breaking.job.yml

  api-schema-check:
    name: API Schema Check
    needs: [ruby-setup, js-setup]
    uses: ./.github/workflows/api-schema-check.job.yml

  e2e-test:
    needs: [ruby-setup, js-setup]
    uses: ./.github/workflows/e2e.job.yml
    secrets: inherit
