name: "Nix build"
on:
  push:
    branches: ["main", "staging", "trying"]
    tags: ["v*"]
    paths-ignore:
      - "CHANGELOG.md"
      - "config/version.rb"
      - "package.json"
  pull_request:
    branches: ["main"]
  merge_group:
    branches: ["main"]
jobs:
  nix-build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    name: "Nix Build (${{ matrix.os }})"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: |
            access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - uses: cachix/cachix-action@v11
        with:
          name: fleetyards
          signingKey: "${{ secrets.CACHIX_SIGNING_KEY }}"
      - run: nix build -L .#fleet_yards_yarn.deps
      - run: nix build -L .#fleet_yards_env
      - run: nix flake check --impure
