name: Release

on:
  push:
    tags: ["v*"]

jobs:
  build:
    uses: ./.github/workflows/build.job.yml
    with:
      tag: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write

  deploy-to-live:
    needs: [build]
    uses: ./.github/workflows/deploy.job.yml
    with:
      destination: live
      name: Live
      url: https://fleetyards.net
    secrets: inherit

  notify_app_signal:
    runs-on: ubuntu-latest
    needs: [deploy-to-live]
    environment: Live
    env:
      APP_SIGNAL_DEPLOY_HOOK: ${{ secrets.APP_SIGNAL_DEPLOY_HOOK }}
    steps:
      - run: |
          curl -X POST "$APP_SIGNAL_DEPLOY_HOOK" \
          -H 'Content-Type: application/json' \
          -d "{\"revision\": \"$GITHUB_SHA\", \"user\": \"${{ github.actor }}\"}"

  create-release:
    needs: [deploy-to-live]
    runs-on: ubuntu-latest
    environment: Live
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Set TAG_NAME
        id: tag
        run: echo "name=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"
      - name: extract Changelog for the current Tag
        run: bundle exec thor changelog:entry "${{ steps.tag.outputs.name }}"
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref }}
          name: ${{ steps.tag.outputs.name }}
          body_path: ${{ steps.tag.outputs.name }}.md
          draft: false
          prerelease: false

  notify-discord:
    runs-on: ubuntu-latest
    needs: [create-release]
    environment: Live
    env:
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
    steps:
      - name: Set TAG_NAME
        id: tag
        run: echo "name=${GITHUB_REF/refs\/tags\//}" >> "$GITHUB_OUTPUT"
      - run: |
          curl -X POST "$DISCORD_WEBHOOK" \
          -H 'Content-Type: application/json' \
          -d "{\"content\": \"**New Release:** ${{ steps.tag.outputs.name }}\nhttps://github.com/fleetyards/fleetyards/releases/tag/${{ steps.tag.outputs.name }}\" }"
