name: Seeds Job

on:
  workflow_call:

jobs:
  seeds:
    runs-on: ubuntu-latest

    env:
      RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
      RAILS_ENV: test
      DATABASE_URL: postgresql://root:root@127.0.0.1:5432/fleetyards_test
      DATABASE_HOST: 127.0.0.1
      DATABASE_USER: root

    services:
      postgres:
        image: postgres:13.2-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_DB: fleetyards_test
          POSTGRES_PASSWORD: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144
      - name: Runs Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 7.6.0
      - run: mkdir -p log
      - run: bundle exec rails db:create db:schema:load
      - name: Create ES Index
        run: bundle exec thor search:index
      - name: Run Seeds
        run: bundle exec rails db:seed
