FORMAT: 1A
HOST: https://api.fleetyards.net

# FleetYards.net API v1

> “Strap into one of dozens of ships and embark on a life within the Star Citizen universe. Unbound by profession or skill sets, you choose the path of your own life.”

This API provides basic Information about All Ships / Components / Manufacturers for the upcomming Space Simulation Star Citizen.

NOTE: This document is a **work in progress**.

<br> 
 
## Current Version

The Current Version is ```v1``` and is included in each Request like this:
```
https://api.fleetyards.net/v1/ships
```

<br>
 
## Schema

All API access is over HTTPS, and accessed from the https://api.fleetyards.net. All data is sent and received as JSON.

Blank fields are included as null instead of being omitted.

<br>
<h3>Timestamps</h3>
All timestamps return in ISO 8601 format:

```
YYYY-MM-DDTHH:MM:SSZ
```

<br>
<h3>Summary Representations</h3>
When you fetch a list of resources, the response includes a subset of the attributes for that resource. This is the "summary" representation of the resource.

Example: When you get a list of models, you get the summary representation of each model:

```
GET /v1/models
```

<br>
<h3>Detailed Representations</h3>
When you fetch an individual resource, the response typically includes all attributes for that resource. This is the "detailed" representation of the resource.

Example: When you get an individual model, you get the detailed representation of the model. Here, we fetch Origins ```300i``` repository:

```
GET /v1/models/300i
```

The documentation provides an example response for each API method. The example response illustrates all attributes that are returned by that method.

<br>
 
## Client Errors


<br>
 
## Authentication

<br>
 
## Limits and Offset

Requests that return multiple items will be limited to ```30``` items by default. 
You can specify further items by increasing the limit or setting the ```offset``` parameter. 
For some resources, you can also set a custom limit up to ```1000```. Note that for technical reasons not all endpoints respect the ```limit``` parameter.

curl 'https://api.fleetyards.net/ships?limit=200&offset=200'

<br>
 
## Rate Limiting


<br>
 
# Group Models

<!-- include(models/index.apib) -->
<!-- include(models/show.apib) -->
<!-- include(models/updates.apib) -->
<!-- include(models/filters.apib) -->

# Group Components

<!-- include(components/categories.apib) -->

# Group Images

<!-- include(images/index.apib) -->
<!-- include(images/updates.apib) -->

# Group Sessions

<!-- include(sessions/create.apib) -->
<!-- include(sessions/destroy.apib) -->

# Group Users

# Group Password

# Group Vehicles

<!-- include(vehicles/private.apib) -->
<!-- include(vehicles/public.apib) -->
<!-- include(vehicles/create.apib) -->
<!-- include(vehicles/update.apib) -->
<!-- include(vehicles/destroy.apib) -->

# Group RSI

<!-- include(rsi.apib) -->

