## Manufacturers [/v1/manufacturers]

### GET Index [GET]
Get a List of Manufacturers

+ Request (application/json)

    + Headers

            Accept: application/json

+ Response 200 (application/json; charset=utf-8)

    + Body

            []
